using System.Globalization;
using System.Text.Json;
using Numerics.Data;
using BestFitRatingCurve = RMC.BestFit.Models.RatingCurve;

namespace RMC.BestFit.Verification.RatingCurve;

/// <summary>
/// Loads the committed rating-curve example fixtures and likelihood oracle that replicate the three
/// synthetic cases of <c>examples/6-rating-curve-analysis</c>, and builds the untouched BestFit
/// rating-curve models used by the Phase 6 rating-curve verification cells.
/// </summary>
/// <remarks>
/// <para>
/// The fixtures artifact <c>rating-curve-example-fixtures.json</c> is generated by
/// <c>verification/python/rating-curve/generate_rating_curve_example_oracles.py</c> from the example
/// workbook's stored uniform draws: stage <c>h = 1 + 19 r1</c> and log10 discharge equal to the
/// addition-mode power law plus <c>0.05 PhiInverse(r2)</c>. It records the 300 daily observations from
/// 2000-01-01, the generating parameters in the BestFit layout, the true curve on a stage grid, the
/// replicated BestFit default bounds, and an independent SciPy conditional maximum-likelihood optimum
/// per case. The likelihood oracle <c>rating-curve-likelihood-oracle.json</c> holds the per-observation
/// log-space Gaussian, base-10 change-of-variables, and discharge-space lognormal density terms.
/// </para>
/// <para>
/// Models are created exactly as the example project configures them: the default flat priors,
/// Jeffreys' rule for the scale, and no change to any <c>BayesianAnalysis</c> setting.
/// </para>
/// </remarks>
internal static class RatingCurveExampleFixtures
{
    /// <summary>The committed fixtures artifact copied to the test output.</summary>
    internal const string FixturesFileName = "rating-curve-example-fixtures.json";

    /// <summary>The committed likelihood oracle copied to the test output.</summary>
    internal const string LikelihoodOracleFileName = "rating-curve-likelihood-oracle.json";

    /// <summary>The number of daily stage/discharge observations in every example case.</summary>
    internal const int Observations = 300;

    /// <summary>The artifact keys of the three example cases.</summary>
    internal static readonly string[] CaseKeys = ["one_segment", "two_segment", "three_segment"];

    /// <summary>
    /// One replicated example case with its generating truth, replicated default bounds, and the
    /// independent SciPy optimum.
    /// </summary>
    /// <param name="Key">The artifact key.</param>
    /// <param name="Segments">The number of segments (controls).</param>
    /// <param name="StartDate">The first observation date.</param>
    /// <param name="Stage">The shared stage observations.</param>
    /// <param name="Discharge">The noisy discharge observations of this case.</param>
    /// <param name="ParameterNames">The BestFit-layout parameter names.</param>
    /// <param name="TrueParameters">The generating parameters in the BestFit layout.</param>
    /// <param name="TrueCurveStages">The stage grid of the true curve.</param>
    /// <param name="TrueCurveDischarge">The true discharge on the stage grid.</param>
    /// <param name="DefaultLowerBounds">The replicated BestFit default lower bounds.</param>
    /// <param name="DefaultUpperBounds">The replicated BestFit default upper bounds.</param>
    /// <param name="LogSpaceLogLikelihoodAtTruth">The log-space Gaussian log likelihood at the truth.</param>
    /// <param name="JacobianSumAtTruth">The sum of the base-10 change-of-variables terms.</param>
    /// <param name="DischargeSpaceLogLikelihoodAtTruth">The discharge-space log likelihood at the truth.</param>
    /// <param name="IndependentMle">The independent SciPy conditional maximum-likelihood optimum.</param>
    /// <param name="IndependentMleLogSpaceLogLikelihood">The log-space log likelihood at the optimum.</param>
    /// <param name="IndependentMleDischargeSpaceLogLikelihood">The discharge-space log likelihood at the optimum.</param>
    /// <param name="IndependentMleResidualSumOfSquares">The log10 residual sum of squares at the optimum.</param>
    /// <param name="ExampleProjectPosteriorMean">The example project's stored posterior mean (documentation only).</param>
    internal sealed record ExampleCase(
        string Key,
        int Segments,
        DateTime StartDate,
        double[] Stage,
        double[] Discharge,
        string[] ParameterNames,
        double[] TrueParameters,
        double[] TrueCurveStages,
        double[] TrueCurveDischarge,
        double[] DefaultLowerBounds,
        double[] DefaultUpperBounds,
        double LogSpaceLogLikelihoodAtTruth,
        double JacobianSumAtTruth,
        double DischargeSpaceLogLikelihoodAtTruth,
        double[] IndependentMle,
        double IndependentMleLogSpaceLogLikelihood,
        double IndependentMleDischargeSpaceLogLikelihood,
        double IndependentMleResidualSumOfSquares,
        double[] ExampleProjectPosteriorMean);

    /// <summary>
    /// Gets the output path of a copied verification artifact.
    /// </summary>
    /// <param name="fileName">The artifact file name.</param>
    /// <returns>The absolute path in the test output directory.</returns>
    internal static string ArtifactPath(string fileName) =>
        Path.Combine(AppContext.BaseDirectory, "VerificationData", fileName);

    /// <summary>
    /// Parses a copied verification artifact.
    /// </summary>
    /// <param name="fileName">The artifact file name.</param>
    /// <returns>The parsed JSON document; the caller disposes it.</returns>
    internal static JsonDocument LoadDocument(string fileName) =>
        JsonDocument.Parse(File.ReadAllText(ArtifactPath(fileName)));

    /// <summary>The number of observations in the seeded 1,000-observation replication block.</summary>
    internal const int ReplicationObservations = 1000;

    /// <summary>
    /// Loads one example case (the shipped 300-observation data) from the fixtures artifact.
    /// </summary>
    /// <param name="key">The artifact key (<c>one_segment</c>, <c>two_segment</c>, or <c>three_segment</c>).</param>
    /// <returns>The detached example case.</returns>
    internal static ExampleCase LoadCase(string key)
    {
        using JsonDocument document = LoadDocument(FixturesFileName);
        JsonElement root = document.RootElement;
        JsonElement metadata = root.GetProperty("metadata");
        return ReadCase(root, metadata, root.GetProperty("cases").GetProperty(key), key, Observations, hasExamplePosteriorMean: true);
    }

    /// <summary>
    /// Loads one recovery case from the seeded 1,000-observation replication block, which applies the
    /// example's exact recipe to a larger draw set (recovery fixtures use between 300 and 1,000
    /// observations; the shipped example has 300).
    /// </summary>
    /// <param name="key">The artifact key (<c>one_segment</c>, <c>two_segment</c>, or <c>three_segment</c>).</param>
    /// <returns>The detached recovery case.</returns>
    internal static ExampleCase LoadReplicationCase(string key)
    {
        using JsonDocument document = LoadDocument(FixturesFileName);
        JsonElement root = document.RootElement.GetProperty("replication_n1000");
        JsonElement metadata = document.RootElement.GetProperty("metadata");
        Assert.AreEqual(ReplicationObservations, root.GetProperty("observations").GetInt32(), "Replication observation count.");
        return ReadCase(root, metadata, root.GetProperty("cases").GetProperty(key), key, ReplicationObservations, hasExamplePosteriorMean: false);
    }

    /// <summary>
    /// Reads one case block and its shared stage series.
    /// </summary>
    /// <param name="block">The block holding <c>stage</c>, <c>start_date</c>, and <c>time_interval</c>.</param>
    /// <param name="metadata">The artifact metadata holding the true-curve stage grid.</param>
    /// <param name="example">The case element.</param>
    /// <param name="key">The case key.</param>
    /// <param name="observations">The expected observation count.</param>
    /// <param name="hasExamplePosteriorMean">Whether the case records the example project's posterior mean.</param>
    /// <returns>The detached case.</returns>
    private static ExampleCase ReadCase(
        JsonElement block,
        JsonElement metadata,
        JsonElement example,
        string key,
        int observations,
        bool hasExamplePosteriorMean)
    {
        JsonElement timing = block.TryGetProperty("time_interval", out _)
            ? block
            : metadata;
        Assert.AreEqual("OneDay", timing.GetProperty("time_interval").GetString(), "Fixture time interval.");
        JsonElement stage = block.GetProperty("stage");
        string[] dates = ReadStrings(stage.GetProperty("dates"));
        double[] stageValues = ReadDoubles(stage.GetProperty("values"));
        Assert.AreEqual(observations, dates.Length, "Fixture date count.");
        Assert.AreEqual(observations, stageValues.Length, "Fixture stage count.");
        DateTime startDate = DateTime.ParseExact(dates[0], "yyyy-MM-dd", CultureInfo.InvariantCulture);
        Assert.AreEqual(
            DateTime.ParseExact(timing.GetProperty("start_date").GetString()!, "yyyy-MM-dd", CultureInfo.InvariantCulture),
            startDate,
            "Fixture start date.");

        JsonElement mle = example.GetProperty("independent_mle");
        JsonElement atTruth = example.GetProperty("log_likelihood_at_truth");
        JsonElement bounds = example.GetProperty("default_bounds");
        double[] discharge = ReadDoubles(example.GetProperty("discharge"));
        Assert.AreEqual(observations, discharge.Length, $"{key} discharge count.");

        return new ExampleCase(
            key,
            example.GetProperty("segments").GetInt32(),
            startDate,
            stageValues,
            discharge,
            ReadStrings(example.GetProperty("parameter_names")),
            ReadDoubles(example.GetProperty("true_parameters")),
            ReadDoubles(metadata.GetProperty("true_curve_stages")),
            ReadDoubles(example.GetProperty("true_curve_discharge")),
            ReadDoubles(bounds.GetProperty("lower")),
            ReadDoubles(bounds.GetProperty("upper")),
            atTruth.GetProperty("log_space").GetDouble(),
            atTruth.GetProperty("jacobian_sum").GetDouble(),
            atTruth.GetProperty("discharge_space").GetDouble(),
            ReadDoubles(mle.GetProperty("parameters")),
            mle.GetProperty("log_space_log_likelihood").GetDouble(),
            mle.GetProperty("discharge_space_log_likelihood").GetDouble(),
            mle.GetProperty("residual_sum_of_squares").GetDouble(),
            hasExamplePosteriorMean ? ReadDoubles(example.GetProperty("example_project_posterior_mean")) : Array.Empty<double>());
    }

    /// <summary>
    /// Creates the stage and discharge daily time series of an example case.
    /// </summary>
    /// <param name="example">The example case.</param>
    /// <returns>The stage and discharge series sharing the fixture dates.</returns>
    internal static (TimeSeries Stage, TimeSeries Discharge) CreateSeries(ExampleCase example) =>
        (new TimeSeries(TimeInterval.OneDay, example.StartDate, example.Stage),
         new TimeSeries(TimeInterval.OneDay, example.StartDate, example.Discharge));

    /// <summary>
    /// Creates the rating-curve model exactly as the example project configures it: the requested
    /// number of segments with the default flat priors and Jeffreys' rule for the scale.
    /// </summary>
    /// <param name="example">The example case.</param>
    /// <returns>An untouched rating-curve model.</returns>
    internal static BestFitRatingCurve CreateModel(ExampleCase example)
    {
        var (stage, discharge) = CreateSeries(example);
        var model = new BestFitRatingCurve(stage, discharge, example.Segments);
        Assert.AreEqual(example.TrueParameters.Length, model.NumberOfParameters, $"{example.Key} parameter count.");
        Assert.IsTrue(model.UseDefaultFlatPriors, $"{example.Key} default flat priors must remain enabled.");
        Assert.IsTrue(model.UseJeffreysRuleForScale, $"{example.Key} Jeffreys' rule for the scale must remain enabled.");
        return model;
    }

    /// <summary>
    /// Reads a JSON array of numbers.
    /// </summary>
    /// <param name="element">The array element.</param>
    /// <returns>The values.</returns>
    internal static double[] ReadDoubles(JsonElement element) =>
        element.EnumerateArray().Select(item => item.GetDouble()).ToArray();

    /// <summary>
    /// Reads a JSON array of strings.
    /// </summary>
    /// <param name="element">The array element.</param>
    /// <returns>The values.</returns>
    internal static string[] ReadStrings(JsonElement element) =>
        element.EnumerateArray().Select(item => item.GetString()!).ToArray();
}
