using Numerics.Distributions;
using RMC.BestFit.Models;
using BestFitDataFrame = RMC.BestFit.Models.DataFrame;

namespace RMC.BestFit.Tests.Univariate;

/// <summary>
/// Unit tests for the <c>CompetingRisksModel</c> class.
/// Tests competing risks models for multiple flood-generating processes.
/// </summary>
/// <remarks>
/// <para>
/// Competing risks models are used when the annual maximum flood can be
/// generated by multiple independent processes (e.g., snowmelt, rainfall,
/// hurricanes). The observed annual maximum is the maximum of all competing
/// processes.
/// </para>
/// <para>
/// This differs from mixture models where data points come from different
/// populations. In competing risks, all processes compete each year to
/// produce the annual maximum.
/// </para>
/// </remarks>
[TestClass]
public class CompetingRisksModelTests
{
    #region Test Data Helper

    /// <summary>
    /// Creates a sample data frame with positive exact observations.
    /// </summary>
    private static BestFitDataFrame CreateSampleDataFrame()
    {
        var df = new BestFitDataFrame();
        var data = new List<ExactData>
        {
            new ExactData { Index = 1990, Value = 1500 },
            new ExactData { Index = 1991, Value = 2000 },
            new ExactData { Index = 1992, Value = 1800 },
            new ExactData { Index = 1993, Value = 2500 },
            new ExactData { Index = 1994, Value = 3000 },
            new ExactData { Index = 1995, Value = 2200 },
            new ExactData { Index = 1996, Value = 3500 },
            new ExactData { Index = 1997, Value = 2800 },
            new ExactData { Index = 1998, Value = 4000 },
            new ExactData { Index = 1999, Value = 3200 }
        };
        df.ExactSeries = new ExactSeries(data);
        return df;
    }

    /// <summary>
    /// Creates a data frame with extreme event characteristics.
    /// </summary>
    private static BestFitDataFrame CreateExtremeEventDataFrame()
    {
        var df = new BestFitDataFrame();
        var data = new List<ExactData>();

        // Regular events
        for (int i = 0; i < 20; i++)
        {
            data.Add(new ExactData { Index = 1980 + i, Value = 1000 + i * 100 });
        }

        // Extreme events (hurricane-like)
        data.Add(new ExactData { Index = 2000, Value = 8000 });
        data.Add(new ExactData { Index = 2005, Value = 10000 });
        data.Add(new ExactData { Index = 2010, Value = 12000 });

        df.ExactSeries = new ExactSeries(data);
        return df;
    }

    /// <summary>
    /// Creates a data frame with interval data.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>IntervalData</c> requires a most-likely <c>Value</c> strictly between
    /// <c>LowerValue</c> and <c>UpperValue</c>; the object-initializer syntax
    /// <c>new IntervalData { Index = ..., LowerValue = ..., UpperValue = ... }</c> leaves
    /// <c>Value = 0</c>, which fails <c>IntervalData.Validate</c> and cascades to
    /// an invalid <c>DataFrame</c>. Use the 4-argument constructor
    /// <c>new IntervalData(index, lower, value, upper)</c> with a mid-point value so the
    /// frame validates and <c>CompetingRisksModel.SetDefaultParameters</c> populates
    /// <c>CompetingRisksModel.Parameters</c>.
    /// </para>
    /// </remarks>
    private static BestFitDataFrame CreateIntervalDataFrame()
    {
        var df = new BestFitDataFrame();
        // At least 4 exact data points are required because
        // <c>Numerics.Data.Statistics.Statistics.ProductMoments</c> returns
        // all-NaN when N &lt; 4 (see Statistics.cs ~line 481) — and NaN initial values
        // later cause Normal.ValidateParameters to throw "The mean must be a number".
        df.ExactSeries = new ExactSeries(new List<ExactData>
        {
            new ExactData { Index = 1990, Value = 2000 },
            new ExactData { Index = 1991, Value = 2500 },
            new ExactData { Index = 1992, Value = 3000 },
            new ExactData { Index = 1993, Value = 2200 },
            new ExactData { Index = 1994, Value = 2700 }
        });
        // 4-arg ctor: index, lowerValue, value (most-likely, must be strictly between lower and upper), upperValue.
        df.IntervalSeries = new IntervalSeries(new List<IntervalData>
        {
            new IntervalData(1800, 4000, 5000, 6000),
            new IntervalData(1850, 5000, 6500, 8000)
        });
        return df;
    }

    #endregion

    #region Constructor Tests

    /// <summary>Verifies that constructor empty constructor creates model.</summary>
    [TestMethod]
    public void Test_Constructor_EmptyConstructor_CreatesModel()
    {
        var model = new CompetingRisksModel();

        Assert.IsNotNull(model);
        Assert.IsTrue(model.UseSingleQuantile);
    }

    /// <summary>Verifies that constructor with distribution types sets components.</summary>
    [TestMethod]
    public void Test_Constructor_WithDistributionTypes_SetsComponents()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,
            UnivariateDistributionType.Gumbel
        };

        var model = new CompetingRisksModel(df, types);

        Assert.IsNotNull(model.CompetingRisks);
        Assert.AreEqual(2, model.CompetingRisks.Distributions.Count);
        Assert.IsInstanceOfType(model.CompetingRisks.Distributions[0], typeof(Normal));
        Assert.IsInstanceOfType(model.CompetingRisks.Distributions[1], typeof(Gumbel));
    }

    /// <summary>Verifies that constructor with competing risks distribution clones distribution.</summary>
    [TestMethod]
    public void Test_Constructor_WithCompetingRisksDistribution_ClonesDistribution()
    {
        var df = CreateSampleDataFrame();
        var dist = new CompetingRisks(new UnivariateDistributionBase[]
        {
            new Normal(2000, 500),
            new Gumbel(2500, 600)
        });

        var model = new CompetingRisksModel(df, dist);

        Assert.IsNotNull(model.CompetingRisks);
        Assert.AreNotSame(dist, model.CompetingRisks);
    }

    /// <summary>Verifies that constructor throws when empty distribution types.</summary>
    [TestMethod]
    [ExpectedException(typeof(ArgumentException))]
    public void Test_Constructor_EmptyDistributionTypes_ThrowsException()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>();

        var model = new CompetingRisksModel(df, types);
    }

    /// <summary>Verifies that constructor throws when too many distributions.</summary>
    [TestMethod]
    [ExpectedException(typeof(ArgumentException))]
    public void Test_Constructor_TooManyDistributions_ThrowsException()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,
            UnivariateDistributionType.Gumbel,
            UnivariateDistributionType.GammaDistribution,
            UnivariateDistributionType.Weibull  // Fourth distribution exceeds limit
        };

        var model = new CompetingRisksModel(df, types);
    }

    /// <summary>Verifies that constructor throws when null distribution.</summary>
    [TestMethod]
    [ExpectedException(typeof(ArgumentNullException))]
    public void Test_Constructor_NullDistribution_ThrowsException()
    {
        var df = CreateSampleDataFrame();
        CompetingRisks? dist = null;

        var model = new CompetingRisksModel(df, dist!);
    }

    #endregion

    #region Property Tests

    /// <summary>Verifies that competing risks set and get.</summary>
    [TestMethod]
    public void Test_CompetingRisks_SetAndGet()
    {
        var model = new CompetingRisksModel();
        var dist = new CompetingRisks(new UnivariateDistributionBase[]
        {
            new Normal(1000, 200),
            new Gumbel(1500, 300)
        });

        model.CompetingRisks = dist;

        Assert.IsNotNull(model.CompetingRisks);
        Assert.AreEqual(2, model.CompetingRisks.Distributions.Count);
    }

    /// <summary>Verifies that use single quantile always returns true.</summary>
    [TestMethod]
    public void Test_UseSingleQuantile_AlwaysReturnsTrue()
    {
        var model = new CompetingRisksModel();

        Assert.IsTrue(model.UseSingleQuantile);

        // Setting to false should be ignored
        model.UseSingleQuantile = false;
        Assert.IsTrue(model.UseSingleQuantile);
    }

    /// <summary>Verifies that data frame set triggers parameter update.</summary>
    [TestMethod]
    public void Test_DataFrame_SetTriggersParameterUpdate()
    {
        var df1 = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,
            UnivariateDistributionType.Gumbel
        };
        var model = new CompetingRisksModel(df1, types);
        int initialCount = model.NumberOfParameters;

        var df2 = CreateExtremeEventDataFrame();
        model.DataFrame = df2;

        // Parameters should still exist after data change
        Assert.IsNotNull(model.Parameters);
        Assert.AreEqual(initialCount, model.NumberOfParameters);
    }

    #endregion

    #region SetDefaultParameters Tests

    /// <summary>Verifies that set default parameters creates parameters for all components.</summary>
    [TestMethod]
    public void Test_SetDefaultParameters_CreatesParametersForAllComponents()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,  // 2 parameters
            UnivariateDistributionType.Gumbel   // 2 parameters
        };
        var model = new CompetingRisksModel(df, types);

        // Should have 4 total parameters (2 + 2)
        Assert.AreEqual(4, model.NumberOfParameters);
    }

    /// <summary>Verifies that set default parameters owner names are set.</summary>
    [TestMethod]
    public void Test_SetDefaultParameters_OwnerNamesAreSet()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,
            UnivariateDistributionType.Gumbel
        };
        var model = new CompetingRisksModel(df, types);

        // First component parameters should have D1 owner
        Assert.AreEqual("D1", model.Parameters[0].OwnerName);
        Assert.AreEqual("D1", model.Parameters[1].OwnerName);

        // Second component parameters should have D2 owner
        Assert.AreEqual("D2", model.Parameters[2].OwnerName);
        Assert.AreEqual("D2", model.Parameters[3].OwnerName);
    }

    /// <summary>Verifies that set default parameters uniform priors.</summary>
    [TestMethod]
    public void Test_SetDefaultParameters_UniformPriors()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        foreach (var param in model.Parameters)
        {
            Assert.IsInstanceOfType(param.PriorDistribution, typeof(Uniform));
        }
    }

    /// <summary>Verifies that set default parameters three components.</summary>
    [TestMethod]
    public void Test_SetDefaultParameters_ThreeComponents()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,      // 2 params
            UnivariateDistributionType.Gumbel,      // 2 params
            UnivariateDistributionType.GammaDistribution  // 2 params
        };
        var model = new CompetingRisksModel(df, types);

        Assert.AreEqual(6, model.NumberOfParameters);
        Assert.IsTrue(model.Parameters.Any(p => p.OwnerName == "D3"));
    }

    #endregion

    #region SetDefaultQuantilePriors Tests

    /// <summary>Verifies that set default quantile priors single quantile.</summary>
    [TestMethod]
    public void Test_SetDefaultQuantilePriors_SingleQuantile()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);
        model.EnableQuantilePriors = true;

        model.SetDefaultQuantilePriors();

        Assert.AreEqual(1, model.QuantilePriors.Count);
    }

    /// <summary>Verifies that set default quantile priors disabled empty list.</summary>
    [TestMethod]
    public void Test_SetDefaultQuantilePriors_Disabled_EmptyList()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);
        model.EnableQuantilePriors = false;

        model.SetDefaultQuantilePriors();

        Assert.AreEqual(0, model.QuantilePriors.Count);
    }

    /// <summary>Verifies that set default quantile priors uses ln normal distribution.</summary>
    [TestMethod]
    public void Test_SetDefaultQuantilePriors_UsesLnNormalDistribution()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);
        model.EnableQuantilePriors = true;

        model.SetDefaultQuantilePriors();

        Assert.IsInstanceOfType(model.QuantilePriors[0].Distribution, typeof(LnNormal));
    }

    #endregion

    #region LogLikelihood Tests

    /// <summary>Verifies that log likelihood returns finite value.</summary>
    [TestMethod]
    public void Test_LogLikelihood_ReturnsFiniteValue()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,
            UnivariateDistributionType.Gumbel
        };
        var model = new CompetingRisksModel(df, types);

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        double logLH = model.LogLikelihood(parameters);

        Assert.IsFalse(double.IsNaN(logLH));
        Assert.IsFalse(double.IsPositiveInfinity(logLH));
    }

    /// <summary>Verifies that data log likelihood returns finite value.</summary>
    [TestMethod]
    public void Test_DataLogLikelihood_ReturnsFiniteValue()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,
            UnivariateDistributionType.Gumbel
        };
        var model = new CompetingRisksModel(df, types);

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        double dataLogLH = model.DataLogLikelihood(parameters);

        Assert.IsFalse(double.IsNaN(dataLogLH));
        Assert.IsFalse(double.IsPositiveInfinity(dataLogLH));
    }

    /// <summary>Verifies that prior log likelihood returns finite value.</summary>
    [TestMethod]
    public void Test_PriorLogLikelihood_ReturnsFiniteValue()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        double priorLogLH = model.PriorLogLikelihood(parameters);

        Assert.IsFalse(double.IsNaN(priorLogLH));
        Assert.IsFalse(double.IsPositiveInfinity(priorLogLH));
    }

    /// <summary>Verifies that log likelihood equals data plus prior.</summary>
    [TestMethod]
    public void Test_LogLikelihood_EqualsDataPlusPrior()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        double fullLogLH = model.LogLikelihood(parameters);
        double dataLogLH = model.DataLogLikelihood(parameters);
        double priorLogLH = model.PriorLogLikelihood(parameters);

        Assert.AreEqual(dataLogLH + priorLogLH, fullLogLH, 1e-6);
    }

    /// <summary>Verifies that pointwise data log likelihood returns correct count.</summary>
    [TestMethod]
    public void Test_PointwiseDataLogLikelihood_ReturnsCorrectCount()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        var pointwise = model.PointwiseDataLogLikelihood(parameters);

        Assert.AreEqual(df.ExactSeries.Count, pointwise.Length);
    }

    /// <summary>Verifies that pointwise data log likelihood sum equals data log likelihood.</summary>
    [TestMethod]
    public void Test_PointwiseDataLogLikelihood_SumEqualsDataLogLikelihood()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        var pointwise = model.PointwiseDataLogLikelihood(parameters);
        double dataLogLH = model.DataLogLikelihood(parameters);

        double sum = pointwise.Sum();
        Assert.AreEqual(dataLogLH, sum, 1e-6);
    }

    #endregion

    #region PointwiseDataLogLikelihoodComponents Tests

    /// <summary>Verifies that pointwise data log likelihood components returns all data points.</summary>
    [TestMethod]
    public void Test_PointwiseDataLogLikelihoodComponents_ReturnsAllDataPoints()
    {
        var df = CreateIntervalDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        var components = model.PointwiseDataLogLikelihoodComponents(parameters);

        // 5 exact + 2 interval = 7 total (exact count raised to meet ProductMoments's N ≥ 4 requirement).
        Assert.AreEqual(7, components.Count);
    }

    /// <summary>Verifies that pointwise data log likelihood components has correct types.</summary>
    [TestMethod]
    public void Test_PointwiseDataLogLikelihoodComponents_HasCorrectTypes()
    {
        var df = CreateIntervalDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        var components = model.PointwiseDataLogLikelihoodComponents(parameters);

        int exactCount = components.Count(c => c.Type == DataComponentType.Exact);
        int intervalCount = components.Count(c => c.Type == DataComponentType.Interval);

        Assert.AreEqual(5, exactCount);
        Assert.AreEqual(2, intervalCount);
    }

    #endregion

    #region PointwisePriorLogLikelihood Tests

    /// <summary>Verifies that pointwise prior log likelihood returns parameter priors.</summary>
    [TestMethod]
    public void Test_PointwisePriorLogLikelihood_ReturnsParameterPriors()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        var priors = model.PointwisePriorLogLikelihood(parameters);

        Assert.IsTrue(priors.Any(p => p.Type == PriorComponentType.ParameterPrior));
    }

    /// <summary>Verifies that pointwise prior log likelihood with jeffreys prior.</summary>
    [TestMethod]
    public void Test_PointwisePriorLogLikelihood_WithJeffreysPrior()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);
        model.UseJeffreysRuleForScale = true;

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        var priors = model.PointwisePriorLogLikelihood(parameters);

        Assert.IsTrue(priors.Any(p => p.Type == PriorComponentType.JeffreysScalePrior));
    }

    /// <summary>Verifies that pointwise prior log likelihood with quantile prior.</summary>
    [TestMethod]
    public void Test_PointwisePriorLogLikelihood_WithQuantilePrior()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);
        model.EnableQuantilePriors = true;
        model.SetDefaultQuantilePriors();
        model.ProcessQuantilePriors();

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        var priors = model.PointwisePriorLogLikelihood(parameters);

        Assert.IsTrue(priors.Any(p => p.Type == PriorComponentType.QuantilePrior));
    }

    #endregion

    #region Clone Tests

    /// <summary>Verifies that clone creates independent copy.</summary>
    [TestMethod]
    public void Test_Clone_CreatesIndependentCopy()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,
            UnivariateDistributionType.Gumbel
        };
        var original = new CompetingRisksModel(df, types);

        var clone = (CompetingRisksModel)original.Clone();

        Assert.AreNotSame(original, clone);
        Assert.AreNotSame(original.CompetingRisks, clone.CompetingRisks);
    }

    /// <summary>Verifies that clone preserves quantile priors for .</summary>
    [TestMethod]
    public void Test_Clone_PreservesQuantilePriors()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var original = new CompetingRisksModel(df, types);
        original.EnableQuantilePriors = true;
        original.SetDefaultQuantilePriors();

        var clone = (CompetingRisksModel)original.Clone();

        Assert.AreEqual(original.QuantilePriors.Count, clone.QuantilePriors.Count);
    }

    /// <summary>Verifies that clone parameters are independent.</summary>
    [TestMethod]
    public void Test_Clone_ParametersAreIndependent()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var original = new CompetingRisksModel(df, types);
        double originalValue = original.Parameters[0].Value;

        var clone = (CompetingRisksModel)original.Clone();
        original.Parameters[0].Value = 99999;

        Assert.AreEqual(originalValue, clone.Parameters[0].Value);
    }

    /// <summary>Verifies that clone preserves jeffreys rule setting for .</summary>
    [TestMethod]
    public void Test_Clone_PreservesJeffreysRuleSetting()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var original = new CompetingRisksModel(df, types);
        original.UseJeffreysRuleForScale = true;

        var clone = (CompetingRisksModel)original.Clone();

        Assert.AreEqual(original.UseJeffreysRuleForScale, clone.UseJeffreysRuleForScale);
    }

    #endregion

    #region Serialization Tests

    /// <summary>Verifies that to X element contains competing risks model element.</summary>
    [TestMethod]
    public void Test_ToXElement_ContainsCompetingRisksModelElement()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,
            UnivariateDistributionType.Gumbel
        };
        var model = new CompetingRisksModel(df, types);

        var xElement = model.ToXElement();

        Assert.AreEqual("CompetingRisksModel", xElement.Name.LocalName);
    }

    /// <summary>Verifies that to X element contains distribution element.</summary>
    [TestMethod]
    public void Test_ToXElement_ContainsDistributionElement()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var xElement = model.ToXElement();

        Assert.IsNotNull(xElement.Element("Distribution"));
    }

    /// <summary>Verifies that to X element contains parameters element.</summary>
    [TestMethod]
    public void Test_ToXElement_ContainsParametersElement()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var xElement = model.ToXElement();

        Assert.IsNotNull(xElement.Element("Parameters"));
    }

    /// <summary>Verifies that to X element contains use single quantile attribute.</summary>
    [TestMethod]
    public void Test_ToXElement_ContainsUseSingleQuantileAttribute()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var xElement = model.ToXElement();

        Assert.IsNotNull(xElement.Attribute("UseSingleQuantile"));
        Assert.AreEqual("True", xElement.Attribute("UseSingleQuantile")?.Value);
    }

    #endregion

    #region Validation Tests

    /// <summary>Verifies that validate returns true when valid model.</summary>
    [TestMethod]
    public void Test_Validate_ValidModel_ReturnsTrue()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,
            UnivariateDistributionType.Gumbel
        };
        var model = new CompetingRisksModel(df, types);

        var (isValid, messages) = model.Validate();

        Assert.IsTrue(isValid, $"Validation failed: {string.Join(", ", messages)}");
    }

    /// <summary>Verifies that validate returns false when null data frame.</summary>
    [TestMethod]
    public void Test_Validate_NullDataFrame_ReturnsFalse()
    {
        var model = new CompetingRisksModel();
        model.DataFrame = null!;

        var (isValid, messages) = model.Validate();

        Assert.IsFalse(isValid);
        Assert.IsTrue(messages.Any(m => m.Contains("Data frame")));
    }

    /// <summary>Verifies that validate returns false when null competing risks.</summary>
    [TestMethod]
    public void Test_Validate_NullCompetingRisks_ReturnsFalse()
    {
        var df = CreateSampleDataFrame();
        var model = new CompetingRisksModel();
        model.DataFrame = df;
        model.CompetingRisks = null;

        var (isValid, messages) = model.Validate();

        Assert.IsFalse(isValid);
        Assert.IsTrue(messages.Any(m => m.Contains("Competing risks")));
    }

    /// <summary>Verifies that validate returns false when too many components.</summary>
    [TestMethod]
    public void Test_Validate_TooManyComponents_ReturnsFalse()
    {
        var df = CreateSampleDataFrame();
        var model = new CompetingRisksModel();
        model.DataFrame = df;

        // Create distribution with 4 components (exceeds limit of 3)
        var dists = new UnivariateDistributionBase[]
        {
            new Normal(100, 10),
            new Normal(200, 20),
            new Normal(300, 30),
            new Normal(400, 40)
        };
        model.CompetingRisks = new CompetingRisks(dists);

        var (isValid, messages) = model.Validate();

        Assert.IsFalse(isValid);
        Assert.IsTrue(messages.Any(m => m.Contains("3")));
    }

    /// <summary>Verifies that validate returns true when single component.</summary>
    [TestMethod]
    public void Test_Validate_SingleComponent_ReturnsTrue()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Gumbel };
        var model = new CompetingRisksModel(df, types);

        var (isValid, messages) = model.Validate();

        Assert.IsTrue(isValid, $"Validation failed: {string.Join(", ", messages)}");
    }

    /// <summary>Verifies that validate returns true when three components.</summary>
    [TestMethod]
    public void Test_Validate_ThreeComponents_ReturnsTrue()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,
            UnivariateDistributionType.Gumbel,
            UnivariateDistributionType.GammaDistribution
        };
        var model = new CompetingRisksModel(df, types);

        var (isValid, messages) = model.Validate();

        Assert.IsTrue(isValid, $"Validation failed: {string.Join(", ", messages)}");
    }

    #endregion

    #region SetParameterValues Tests

    /// <summary>Verifies that set parameter values updates parameters.</summary>
    [TestMethod]
    public void Test_SetParameterValues_UpdatesParameters()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var newValues = new double[] { 2500.0, 750.0 };
        model.SetParameterValues(newValues);

        Assert.AreEqual(2500.0, model.Parameters[0].Value);
        Assert.AreEqual(750.0, model.Parameters[1].Value);
    }

    /// <summary>Verifies that set parameter values updates distribution.</summary>
    [TestMethod]
    public void Test_SetParameterValues_UpdatesDistribution()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var newValues = new double[] { 3000.0, 500.0 };
        model.SetParameterValues(newValues);

        // Distribution parameters should be updated
        var normal = (Normal)model.CompetingRisks!.Distributions[0];
        Assert.AreEqual(3000.0, normal.Mu, 1e-10);
        Assert.AreEqual(500.0, normal.Sigma, 1e-10);
    }

    /// <summary>Verifies that set parameter values throws when null parameters.</summary>
    [TestMethod]
    [ExpectedException(typeof(ArgumentNullException))]
    public void Test_SetParameterValues_NullParameters_ThrowsException()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        model.SetParameterValues(null!);
    }

    /// <summary>Verifies that set parameter values throws when wrong count.</summary>
    [TestMethod]
    [ExpectedException(typeof(ArgumentException))]
    public void Test_SetParameterValues_WrongCount_ThrowsException()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var wrongCount = new double[] { 1.0 };  // Should be 2 for Normal
        model.SetParameterValues(wrongCount);
    }

    #endregion

    #region Engineering Application Tests

    /// <summary>Verifies that competing risks snowmelt vs rainfall.</summary>
    [TestMethod]
    public void Test_CompetingRisks_SnowmeltVsRainfall()
    {
        // Snowmelt floods (spring) vs rainfall floods (summer/fall)
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,  // Snowmelt
            UnivariateDistributionType.Gumbel   // Rainfall
        };
        var model = new CompetingRisksModel(df, types);

        var (isValid, _) = model.Validate();
        Assert.IsTrue(isValid);

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        double logLH = model.LogLikelihood(parameters);
        Assert.IsFalse(double.IsNegativeInfinity(logLH));
    }

    /// <summary>Verifies that competing risks with hurricanes.</summary>
    [TestMethod]
    public void Test_CompetingRisks_WithHurricanes()
    {
        // Regular floods vs hurricane-induced floods
        var df = CreateExtremeEventDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,              // Regular
            UnivariateDistributionType.GeneralizedExtremeValue  // Hurricanes
        };
        var model = new CompetingRisksModel(df, types);

        var (isValid, _) = model.Validate();
        Assert.IsTrue(isValid);
    }

    /// <summary>Verifies that competing risks three seasons.</summary>
    [TestMethod]
    public void Test_CompetingRisks_ThreeSeasons()
    {
        // Spring snowmelt, summer thunderstorms, fall tropical systems
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,
            UnivariateDistributionType.Gumbel,
            UnivariateDistributionType.GeneralizedExtremeValue
        };
        var model = new CompetingRisksModel(df, types);

        var (isValid, _) = model.Validate();
        Assert.IsTrue(isValid);

        Assert.AreEqual(3, model.CompetingRisks!.Distributions.Count);
    }

    #endregion

    #region Jeffreys Prior Tests

    /// <summary>Verifies that jeffreys prior affects prior log likelihood.</summary>
    [TestMethod]
    public void Test_JeffreysPrior_AffectsPriorLogLikelihood()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var parameters = model.Parameters.Select(p => p.Value).ToArray();

        model.UseJeffreysRuleForScale = false;
        double priorNoJeffreys = model.PriorLogLikelihood(parameters);

        model.UseJeffreysRuleForScale = true;
        double priorWithJeffreys = model.PriorLogLikelihood(parameters);

        // Jeffreys prior adds -log(scale) term
        Assert.AreNotEqual(priorNoJeffreys, priorWithJeffreys);
    }

    /// <summary>Verifies that jeffreys prior gamma distribution uses first parameter.</summary>
    [TestMethod]
    public void Test_JeffreysPrior_GammaDistribution_UsesFirstParameter()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.GammaDistribution };
        var model = new CompetingRisksModel(df, types);
        model.UseJeffreysRuleForScale = true;

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        var priors = model.PointwisePriorLogLikelihood(parameters);

        // Should have Jeffreys scale prior for Gamma's first parameter
        Assert.IsTrue(priors.Any(p => p.Type == PriorComponentType.JeffreysScalePrior));
    }

    /// <summary>Verifies that jeffreys prior weibull uses first parameter.</summary>
    [TestMethod]
    public void Test_JeffreysPrior_Weibull_UsesFirstParameter()
    {
        var df = CreateSampleDataFrame();
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Weibull };
        var model = new CompetingRisksModel(df, types);
        model.UseJeffreysRuleForScale = true;

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        var priors = model.PointwisePriorLogLikelihood(parameters);

        // Should have Jeffreys scale prior for Weibull's first parameter (scale)
        Assert.IsTrue(priors.Any(p => p.Type == PriorComponentType.JeffreysScalePrior));
    }

    #endregion

    #region Edge Cases

    /// <summary>Verifies that competing risks single data point.</summary>
    [TestMethod]
    public void Test_CompetingRisks_SingleDataPoint()
    {
        var df = new BestFitDataFrame();
        df.ExactSeries = new ExactSeries(new List<ExactData>
        {
            new ExactData { Index = 2000, Value = 1000 }
        });
        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };

        var model = new CompetingRisksModel(df, types);

        Assert.IsNotNull(model.CompetingRisks);
    }

    /// <summary>Verifies that competing risks large values.</summary>
    [TestMethod]
    public void Test_CompetingRisks_LargeValues()
    {
        var df = new BestFitDataFrame();
        var data = new List<ExactData>();
        for (int i = 0; i < 10; i++)
        {
            data.Add(new ExactData { Index = 2000 + i, Value = 1e8 + i * 1e6 });
        }
        df.ExactSeries = new ExactSeries(data);

        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var (isValid, _) = model.Validate();
        Assert.IsTrue(isValid);
    }

    /// <summary>Verifies that competing risks small values.</summary>
    [TestMethod]
    public void Test_CompetingRisks_SmallValues()
    {
        var df = new BestFitDataFrame();
        var data = new List<ExactData>();
        for (int i = 0; i < 10; i++)
        {
            data.Add(new ExactData { Index = 2000 + i, Value = 0.001 + i * 0.0001 });
        }
        df.ExactSeries = new ExactSeries(data);

        var types = new List<UnivariateDistributionType> { UnivariateDistributionType.Normal };
        var model = new CompetingRisksModel(df, types);

        var (isValid, _) = model.Validate();
        Assert.IsTrue(isValid);
    }

    /// <summary>Verifies that competing risks with interval data.</summary>
    [TestMethod]
    public void Test_CompetingRisks_WithIntervalData()
    {
        var df = CreateIntervalDataFrame();
        var types = new List<UnivariateDistributionType>
        {
            UnivariateDistributionType.Normal,
            UnivariateDistributionType.Gumbel
        };
        var model = new CompetingRisksModel(df, types);

        var parameters = model.Parameters.Select(p => p.Value).ToArray();
        double logLH = model.LogLikelihood(parameters);

        Assert.IsFalse(double.IsNaN(logLH));
    }

    #endregion
}
