using System.Text.Json;
using Numerics.Distributions;
using RMC.BestFit.Diagnostics;
using RMC.BestFit.Estimation;
using RMC.BestFit.Models;

namespace RMC.BestFit.Verification.ModelEstimation;

/// <summary>
/// Verifies GMM fit influence, variance influence, and combined leverage against
/// an independent R <c>gmm</c> implementation on a Log10-Normal moment fixture.
/// </summary>
/// <remarks>
/// The committed artifact is generated by R 4.4.3, <c>gmm</c> 1.9.1, and
/// <c>sandwich</c> 3.1.2. R is not required when these focused methods execute.
/// Cook distance is compared only within the GMM estimating-equation framework;
/// its magnitude is not equated with likelihood-based MAP Cook distance.
/// </remarks>
[TestClass]
public class GmmInfluenceDiagnosticsVerificationTests
{
    /// <summary>
    /// Verifies every observation and aggregate diagnostic against the pinned R
    /// <c>gmm</c> score-and-bread calculation.
    /// </summary>
    /// <remarks>
    /// The R oracle uses <c>e_i=D'Wg_i</c>, <c>B=D'WD</c>, Cook influence
    /// <c>e_i'B^-1e_i/(n^2 p)</c>, and variance influence
    /// <c>e_i'B^-1e_i/(n p)</c>. BestFit estimates the diagnostic objective Hessian
    /// numerically, so the artifact predeclares a <c>1e-5</c> absolute tolerance.
    /// </remarks>
    [TestMethod]
    public void Log10NormalObservationInfluence_MatchesRGmmOracle()
    {
        JsonElement oracle = LoadOracle();
        double[] log10Values = ReadArray(oracle.GetProperty("data_log10"));
        var gmm = FitGmm(log10Values, null, null);
        LeverageDiagnostics diagnostics = gmm.GetLeverageDiagnostics();
        JsonElement expectedObservations = oracle.GetProperty("observations");
        JsonElement metadata = oracle.GetProperty("metadata");
        double fitTolerance = metadata.GetProperty("fit_influence_absolute_tolerance").GetDouble();
        double varianceTolerance = metadata.GetProperty("variance_influence_absolute_tolerance").GetDouble();
        double combinedTolerance = metadata.GetProperty("combined_leverage_absolute_tolerance").GetDouble();

        Assert.AreEqual(expectedObservations.GetArrayLength(), diagnostics.Observations.Length);
        int observationIndex = 0;
        foreach (JsonElement expected in expectedObservations.EnumerateArray())
        {
            LeverageDiagnostics.ObservationLeverage actual = diagnostics.Observations[observationIndex];
            Assert.AreEqual(expected.GetProperty("index").GetInt32(), actual.Index);
            Assert.AreEqual(
                expected.GetProperty("fit_influence").GetDouble(),
                actual.FitInfluence,
                fitTolerance,
                $"Observation {observationIndex} GMM Cook influence differs from R gmm.");
            Assert.AreEqual(
                expected.GetProperty("variance_influence").GetDouble(),
                actual.VarianceInfluence,
                varianceTolerance,
                $"Observation {observationIndex} GMM variance influence differs from R gmm.");
            Assert.AreEqual(
                expected.GetProperty("combined_leverage").GetDouble(),
                actual.Leverage,
                combinedTolerance,
                $"Observation {observationIndex} combined leverage differs from R gmm.");
            observationIndex++;
        }

        JsonElement totals = oracle.GetProperty("totals");
        Assert.AreEqual(
            totals.GetProperty("fit_influence").GetDouble(),
            diagnostics.TotalFitInfluence,
            fitTolerance,
            "Total GMM Cook influence differs from R gmm.");
        Assert.AreEqual(
            totals.GetProperty("variance_influence").GetDouble(),
            diagnostics.TotalVarianceInfluence,
            varianceTolerance,
            "Total GMM variance influence differs from R gmm.");
        Assert.AreEqual(
            totals.GetProperty("combined_leverage").GetDouble(),
            diagnostics.TotalLeverage,
            combinedTolerance,
            "Total combined leverage differs from R gmm.");
    }

    /// <summary>
    /// Verifies that merely enabling a centered, effectively flat quadratic penalty
    /// does not change the observation diagnostic scale.
    /// </summary>
    /// <remarks>
    /// A finite width of one hundred likelihood standard errors is used so the penalty
    /// path remains numerically active while its effect is negligible. The <c>1e-4</c>
    /// equivalence tolerance covers that deliberately finite curvature and numerical
    /// Hessian evaluation; it does not relax the external R parity tolerance.
    /// </remarks>
    [TestMethod]
    public void VanishingCenteredPenalty_PreservesObservationInfluenceScale()
    {
        JsonElement oracle = LoadOracle();
        double[] log10Values = ReadArray(oracle.GetProperty("data_log10"));
        var unpenalized = FitGmm(log10Values, null, null);
        double likelihoodStandardError = unpenalized.BestParameterSet.Values[1] / Math.Sqrt(log10Values.Length);
        var wideCentered = FitGmm(
            log10Values,
            unpenalized.BestParameterSet.Values[0],
            100d * likelihoodStandardError);
        LeverageDiagnostics unpenalizedDiagnostics = unpenalized.GetLeverageDiagnostics();
        LeverageDiagnostics wideDiagnostics = wideCentered.GetLeverageDiagnostics();
        double tolerance = oracle.GetProperty("metadata")
            .GetProperty("vanishing_penalty_equivalence_absolute_tolerance")
            .GetDouble();

        Assert.AreEqual(unpenalizedDiagnostics.Observations.Length, wideDiagnostics.Observations.Length);
        for (int i = 0; i < unpenalizedDiagnostics.Observations.Length; i++)
        {
            Assert.AreEqual(
                unpenalizedDiagnostics.Observations[i].FitInfluence,
                wideDiagnostics.Observations[i].FitInfluence,
                tolerance,
                $"Observation {i} Cook influence changed when a vanishing penalty was enabled.");
            Assert.AreEqual(
                unpenalizedDiagnostics.Observations[i].VarianceInfluence,
                wideDiagnostics.Observations[i].VarianceInfluence,
                tolerance,
                $"Observation {i} variance influence changed materially under a vanishing penalty.");
            Assert.AreEqual(
                unpenalizedDiagnostics.Observations[i].Leverage,
                wideDiagnostics.Observations[i].Leverage,
                tolerance,
                $"Observation {i} combined leverage changed materially under a vanishing penalty.");
        }
    }

    /// <summary>
    /// Fits the just-identified Bulletin 17C Log10-Normal GMM model with an optional
    /// Gaussian-equivalent quadratic penalty on mu.
    /// </summary>
    /// <param name="log10Values">The observations in base-10 log space.</param>
    /// <param name="penaltyMean">The penalty mean, or <see langword="null"/> for no penalty.</param>
    /// <param name="penaltyStandardDeviation">The Gaussian-equivalent standard deviation, or <see langword="null"/>.</param>
    /// <returns>The fitted GMM estimator.</returns>
    private static GeneralizedMethodOfMoments FitGmm(
        double[] log10Values,
        double? penaltyMean,
        double? penaltyStandardDeviation)
    {
        var model = new Bulletin17CDistribution(
            CreateDataFrame(log10Values),
            UnivariateDistributionType.LogNormal);
        if (penaltyMean.HasValue && penaltyStandardDeviation.HasValue)
        {
            model.ParameterPenalties[0].Enabled = true;
            model.ParameterPenalties[0].Mean = penaltyMean.Value;
            model.ParameterPenalties[0].MSE =
                penaltyStandardDeviation.Value * penaltyStandardDeviation.Value;
            model.ParameterPenalties[0].UseLog = false;
            model.SetPenaltyFunction();
        }

        var estimator = new GeneralizedMethodOfMoments(model, OptimizationMethod.BFGS)
        {
            EstimationStrategy = GeneralizedMethodOfMoments.GMMEstimationStrategy.Iterative,
            UseFallbackOptimizer = false,
            MaxFunctionEvaluations = 10000,
            MaxGMMIterations = 100,
            AbsoluteTolerance = 1E-10d,
            RelativeTolerance = 1E-10d
        };

        Assert.IsTrue(estimator.Estimate(), "The deterministic Log10-Normal GMM fit must converge.");
        return estimator;
    }

    /// <summary>
    /// Creates an exact-data frame from base-10 log observations.
    /// </summary>
    /// <param name="log10Values">The observations in base-10 log space.</param>
    /// <returns>The data frame on the original positive scale.</returns>
    private static DataFrame CreateDataFrame(double[] log10Values)
    {
        return new DataFrame
        {
            ExactSeries = new ExactSeries(log10Values.Select(value => Math.Pow(10d, value)).ToArray())
        };
    }

    /// <summary>
    /// Loads and clones the committed R <c>gmm</c> oracle root.
    /// </summary>
    /// <returns>A detached JSON root element.</returns>
    private static JsonElement LoadOracle()
    {
        string path = Path.Combine(
            AppContext.BaseDirectory,
            "VerificationData",
            "gmm-influence-oracle.json");
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(path));
        return document.RootElement.Clone();
    }

    /// <summary>
    /// Reads a JSON numeric array into managed doubles.
    /// </summary>
    /// <param name="element">JSON array element.</param>
    /// <returns>The array values.</returns>
    private static double[] ReadArray(JsonElement element)
    {
        var values = new double[element.GetArrayLength()];
        int index = 0;
        foreach (JsonElement value in element.EnumerateArray())
        {
            values[index++] = value.GetDouble();
        }
        return values;
    }
}
