using DatabaseManager;
using FrameworkInterfaces.Undo;
using OxyPlot.Wpf;
using OxyPlot.Wpf.Serialization;
using RMC.BestFit.Estimation;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;
using System.Windows;
using System.Windows.Media;
using System.Xml.Linq;

namespace RMC.BestFit.UI
{
    /// <summary>
    /// Manages Bayesian MCMC diagnostic plots, settings undo-redo, and MCMC report storage
    /// for all analysis elements that use Bayesian estimation.
    /// </summary>
    /// <remarks>
    /// <para>
    ///     Authors:
    ///     Haden Smith, USACE Risk Management Center, cole.h.smith@usace.army.mil
    /// </para>
    /// <para>
    /// This class centralizes three concerns shared by all Bayesian analysis UI elements:
    /// <list type="number">
    /// <item><description><b>Diagnostic plots</b> — Ownership, undo bridges, and serialization for the 7 standard
    /// MCMC diagnostic plots (trace, histogram, kernel density, autocorrelation, mean likelihood,
    /// bivariate heat map, influence diagnostics).</description></item>
    /// <item><description><b>BayesianAnalysis settings undo-redo</b> — Conditional property change recording for
    /// simulation parameters, with correct suppression when UseSimulationDefaults/UseAdvancedSimulationDefaults
    /// are active.</description></item>
    /// <item><description><b>MCMC report</b> — Cached report text generated by <see cref="BayesianAnalysis.GenerateReport()"/>
    /// and persisted to the database.</description></item>
    /// </list>
    /// </para>
    /// <para>
    /// Composed into analysis UI elements (e.g., UnivariateAnalysis, MixtureAnalysis) rather than
    /// each element managing these independently. The owning element delegates bridge setup,
    /// suspension, serialization, and disposal to this class.
    /// </para>
    /// </remarks>
    public class BayesianController : IDisposable
    {

        #region Construction

        /// <summary>
        /// Initializes a new instance of the <see cref="BayesianController"/> class.
        /// Creates all 7 default diagnostic plots with standard axis configurations.
        /// </summary>
        /// <remarks>
        /// Bridges are NOT created in the constructor. The owning element must call
        /// <see cref="SetupBridges"/> after construction and after Open()/Copy() to
        /// connect the plots to the element's undo manager.
        /// </remarks>
        public BayesianController()
        {
            _markovChainTracePlot = CreateDefaultMarkovChainTracePlot();
            _histogramPlot = CreateDefaultHistogramPlot();
            _kernelDensityPlot = CreateDefaultKernelDensityPlot();
            _autocorrelationPlot = CreateDefaultAutocorrelationPlot();
            _meanLikelihoodPlot = CreateDefaultMeanLikelihoodPlot();
            _bivariateHeatMapPlot = CreateDefaultBivariateHeatMapPlot();
            _influenceDiagnosticsPlot = CreateDefaultInfluenceDiagnosticsPlot();
        }

        #endregion

        #region Members

        #region Fields

        /// <summary>
        /// The Markov chain trace plot showing parameter evolution across MCMC iterations.
        /// </summary>
        private Plot _markovChainTracePlot;

        /// <summary>
        /// The posterior histogram plot showing the distribution of sampled parameter values.
        /// </summary>
        private Plot _histogramPlot;

        /// <summary>
        /// The kernel density estimate plot showing a smoothed posterior density curve.
        /// </summary>
        private Plot _kernelDensityPlot;

        /// <summary>
        /// The autocorrelation plot showing lag-correlation of MCMC samples for convergence diagnostics.
        /// </summary>
        private Plot _autocorrelationPlot;

        /// <summary>
        /// The mean log-likelihood plot showing convergence of the log-likelihood across iterations.
        /// </summary>
        private Plot _meanLikelihoodPlot;

        /// <summary>
        /// The bivariate heat map plot showing the joint posterior density of two parameters.
        /// </summary>
        private Plot _bivariateHeatMapPlot;

        /// <summary>
        /// The influence diagnostics tornado plot showing per-observation and per-prior influence.
        /// </summary>
        private Plot _influenceDiagnosticsPlot;

        /// <summary>
        /// Undo manager for the Markov chain trace plot.
        /// </summary>
        private PlotUndoManager _markovChainTracePlotUndo;

        /// <summary>
        /// Undo manager for the posterior histogram plot.
        /// </summary>
        private PlotUndoManager _histogramPlotUndo;

        /// <summary>
        /// Undo manager for the kernel density estimate plot.
        /// </summary>
        private PlotUndoManager _kernelDensityPlotUndo;

        /// <summary>
        /// Undo manager for the autocorrelation plot.
        /// </summary>
        private PlotUndoManager _autocorrelationPlotUndo;

        /// <summary>
        /// Undo manager for the mean log-likelihood plot.
        /// </summary>
        private PlotUndoManager _meanLikelihoodPlotUndo;

        /// <summary>
        /// Undo manager for the bivariate heat map plot.
        /// </summary>
        private PlotUndoManager _bivariateHeatMapPlotUndo;

        /// <summary>
        /// Undo manager for the influence diagnostics tornado plot.
        /// </summary>
        private PlotUndoManager _influenceDiagnosticsPlotUndo;

        /// <summary>
        /// Whether this instance has been disposed.
        /// </summary>
        private bool _isDisposed;

        // --- BayesianAnalysis settings undo infrastructure ---

        /// <summary>
        /// Bridge for BayesianAnalysis properties that are always recorded (UseDefaults flags,
        /// Type, PointEstimator, CredibleIntervalWidth, OutputLength).
        /// </summary>
        private UndoableStateBridge _bayesianAlwaysBridge;

        /// <summary>
        /// Bridge for simulation properties (Iterations, WarmupIterations, etc.).
        /// Always alive to maintain baseline values. Recording is gated by <see cref="_simulationUndoEnabled"/>
        /// which returns null from the getUndo lambda when UseDefaults is true.
        /// </summary>
        private UndoableStateBridge _simulationPropsBridge;

        /// <summary>
        /// Whether the simulation bridge should record. False when UseSimulationDefaults is true.
        /// </summary>
        private bool _simulationUndoEnabled;

        /// <summary>
        /// Bridge for advanced simulation properties (Jump, Noise, etc.).
        /// Same gating pattern via <see cref="_advancedUndoEnabled"/>.
        /// </summary>
        private UndoableStateBridge _advancedPropsBridge;

        /// <summary>
        /// Whether the advanced bridge should record. False when UseAdvancedSimulationDefaults is true.
        /// </summary>
        private bool _advancedUndoEnabled;

        /// <summary>
        /// The currently monitored <see cref="BayesianAnalysis"/> for UseDefaults flag changes.
        /// </summary>
        private BayesianAnalysis _subscribedBayesianAnalysis;

        /// <summary>
        /// Captured <see cref="IUndoManager"/> resolver from the owning element. Returns the
        /// active manager when <c>IsUndoEnabled</c> is true and null otherwise; cached here so
        /// conditional bridges (recreated when <see cref="BayesianAnalysis.UseSimulationDefaults"/>
        /// flips) can be rebuilt without re-passing it from the owner each time.
        /// </summary>
        private Func<IUndoManager> _getUndo;

        /// <summary>
        /// Captured "mark dirty" callback from the owning element. Invoked after every recorded
        /// undo action so the project's IsDirty flag tracks the change.
        /// </summary>
        private Action _onRecorded;

        /// <summary>
        /// Captured target instance (the owning element) used to disambiguate undo entries
        /// when the project tree contains many elements with similar bridges.
        /// </summary>
        private object _target;

        /// <summary>
        /// Callback invoked when any BayesianAnalysis property changes (including during undo)
        /// so the owning element can refresh validation. Set during <see cref="SetupBridges"/>.
        /// </summary>
        private Action _onValidate;

        // --- MCMC Report ---

        /// <summary>
        /// Cached MCMC report text generated by <see cref="BayesianAnalysis.GenerateReport()"/>.
        /// </summary>
        private string _mcmcReport;

        #endregion

        #region Static Property Lists

        /// <summary>
        /// Simulation option properties — only recorded when <see cref="BayesianAnalysis.UseSimulationDefaults"/> is false.
        /// </summary>
        public static readonly string[] SimulationDefaultsProperties = new[]
        {
            nameof(BayesianAnalysis.Iterations),
            nameof(BayesianAnalysis.WarmupIterations),
            nameof(BayesianAnalysis.ThinningInterval),
            nameof(BayesianAnalysis.NumberOfChains),
            nameof(BayesianAnalysis.PRNGSeed),
            nameof(BayesianAnalysis.InitialIterations)
        };

        /// <summary>
        /// Advanced simulation option properties — only recorded when <see cref="BayesianAnalysis.UseAdvancedSimulationDefaults"/> is false.
        /// </summary>
        public static readonly string[] AdvancedDefaultsProperties = new[]
        {
            nameof(BayesianAnalysis.Jump),
            nameof(BayesianAnalysis.JumpThreshold),
            nameof(BayesianAnalysis.SnookerThreshold),
            nameof(BayesianAnalysis.Noise),
            nameof(BayesianAnalysis.Scale),
            nameof(BayesianAnalysis.Beta),
            nameof(BayesianAnalysis.MaxTreeDepth)
        };

        /// <summary>
        /// <see cref="BayesianAnalysis"/> properties that are always recorded as undo actions
        /// regardless of UseDefaults flags, because the user always sets these directly.
        /// </summary>
        public static readonly string[] AlwaysRecordProperties = new[]
        {
            nameof(BayesianAnalysis.UseSimulationDefaults),
            nameof(BayesianAnalysis.UseAdvancedSimulationDefaults),
            nameof(BayesianAnalysis.Type),
            nameof(BayesianAnalysis.PointEstimator),
            nameof(BayesianAnalysis.CredibleIntervalWidth),
            nameof(BayesianAnalysis.OutputLength)
        };

        #endregion

        #region Properties

        /// <summary>
        /// Gets the Markov chain trace plot showing parameter evolution across MCMC iterations.
        /// </summary>
        public Plot MarkovChainTracePlot => _markovChainTracePlot;

        /// <summary>
        /// Gets the posterior histogram plot showing the distribution of sampled parameter values.
        /// </summary>
        public Plot HistogramPlot => _histogramPlot;

        /// <summary>
        /// Gets the kernel density estimate plot showing a smoothed posterior density curve.
        /// </summary>
        public Plot KernelDensityPlot => _kernelDensityPlot;

        /// <summary>
        /// Gets the autocorrelation plot showing lag-correlation of MCMC samples for convergence diagnostics.
        /// </summary>
        public Plot AutocorrelationPlot => _autocorrelationPlot;

        /// <summary>
        /// Gets the mean log-likelihood plot showing convergence of the log-likelihood across iterations.
        /// </summary>
        public Plot MeanLikelihoodPlot => _meanLikelihoodPlot;

        /// <summary>
        /// Gets the bivariate heat map plot showing the joint posterior density of two parameters.
        /// </summary>
        public Plot BivariateHeatMapPlot => _bivariateHeatMapPlot;

        /// <summary>
        /// Gets the influence diagnostics tornado plot showing per-observation and per-prior influence.
        /// </summary>
        public Plot InfluenceDiagnosticsPlot => _influenceDiagnosticsPlot;

        /// <summary>
        /// Gets the cached MCMC report text.
        /// </summary>
        public string MCMCReport => _mcmcReport;

        #endregion

        #endregion

        #region Bridge Management

        /// <summary>
        /// Sets up undo bridges for all 7 diagnostic plots and BayesianAnalysis conditional undo recording.
        /// </summary>
        /// <param name="getUndo">Lambda returning the <see cref="IUndoManager"/> when undo is enabled, or null.</param>
        /// <param name="target">The owning element, used as the undo action target.</param>
        /// <param name="onRecorded">Callback invoked when any bridge records an undo action (typically <c>SetIsDirty(true)</c>).</param>
        /// <param name="bayesianAnalysis">The <see cref="BayesianAnalysis"/> instance to monitor for property changes. May be null.</param>
        /// <param name="onValidate">Callback invoked after Bayesian settings changes require element validation.</param>
        /// <remarks>
        /// Called by the owning element after construction and after Open()/Copy().
        /// Disposes any existing bridges before creating new ones.
        /// </remarks>
        public void SetupBridges(Func<IUndoManager> getUndo, object target, Action onRecorded,
            BayesianAnalysis bayesianAnalysis = null, Action onValidate = null)
        {
            if (_isDisposed)
                throw new ObjectDisposedException(nameof(BayesianController),
                    "Cannot rebuild bridges on a disposed BayesianController. Recreate the controller " +
                    "via the owning element if bridges need to be re-established after Dispose().");
            DisposeBridges();
            _getUndo = getUndo;
            _onRecorded = onRecorded;
            _target = target;
            _onValidate = onValidate;

            if (_markovChainTracePlot != null)
                _markovChainTracePlotUndo = new PlotUndoManager(_markovChainTracePlot, getUndo, "MCMC trace plot", target, onRecorded);
            if (_histogramPlot != null)
                _histogramPlotUndo = new PlotUndoManager(_histogramPlot, getUndo, "histogram plot", target, onRecorded);
            if (_kernelDensityPlot != null)
                _kernelDensityPlotUndo = new PlotUndoManager(_kernelDensityPlot, getUndo, "kernel density plot", target, onRecorded);
            if (_autocorrelationPlot != null)
                _autocorrelationPlotUndo = new PlotUndoManager(_autocorrelationPlot, getUndo, "autocorrelation plot", target, onRecorded);
            if (_meanLikelihoodPlot != null)
                _meanLikelihoodPlotUndo = new PlotUndoManager(_meanLikelihoodPlot, getUndo, "mean likelihood plot", target, onRecorded);
            if (_bivariateHeatMapPlot != null)
                _bivariateHeatMapPlotUndo = new PlotUndoManager(_bivariateHeatMapPlot, getUndo, "bivariate heat map plot", target, onRecorded);
            if (_influenceDiagnosticsPlot != null)
                _influenceDiagnosticsPlotUndo = new PlotUndoManager(_influenceDiagnosticsPlot, getUndo, "influence diagnostics plot", target, onRecorded);

            // BayesianAnalysis undo bridges
            SetupBayesianBridges(bayesianAnalysis);
        }

        /// <summary>
        /// Disposes all undo bridges for the 7 diagnostic plots.
        /// </summary>
        /// <remarks>
        /// Called before creating new bridges in <see cref="SetupBridges"/> and during <see cref="Dispose"/>.
        /// Safe to call multiple times.
        /// </remarks>
        public void DisposeBridges()
        {
            DisposeBayesianBridges();

            _markovChainTracePlotUndo?.Dispose();
            _markovChainTracePlotUndo = null;
            _histogramPlotUndo?.Dispose();
            _histogramPlotUndo = null;
            _kernelDensityPlotUndo?.Dispose();
            _kernelDensityPlotUndo = null;
            _autocorrelationPlotUndo?.Dispose();
            _autocorrelationPlotUndo = null;
            _meanLikelihoodPlotUndo?.Dispose();
            _meanLikelihoodPlotUndo = null;
            _bivariateHeatMapPlotUndo?.Dispose();
            _bivariateHeatMapPlotUndo = null;
            _influenceDiagnosticsPlotUndo?.Dispose();
            _influenceDiagnosticsPlotUndo = null;
        }

        /// <summary>
        /// Suspends undo recording for all 7 diagnostic plot undo managers.
        /// </summary>
        /// <returns>An <see cref="IDisposable"/> that resumes recording when disposed.</returns>
        /// <remarks>
        /// Use this when performing bulk plot operations (e.g., clearing and adding data series)
        /// that should not be recorded as individual undo actions. After disposing the returned token,
        /// call <see cref="RebuildSeriesAndAnnotationBridges"/> to reconnect bridges.
        /// </remarks>
        public IDisposable SuspendPlotBridges()
        {
            var suspensions = new List<IDisposable>();
            if (_markovChainTracePlotUndo != null) suspensions.Add(_markovChainTracePlotUndo.SuspendRecording());
            if (_histogramPlotUndo != null) suspensions.Add(_histogramPlotUndo.SuspendRecording());
            if (_kernelDensityPlotUndo != null) suspensions.Add(_kernelDensityPlotUndo.SuspendRecording());
            if (_autocorrelationPlotUndo != null) suspensions.Add(_autocorrelationPlotUndo.SuspendRecording());
            if (_meanLikelihoodPlotUndo != null) suspensions.Add(_meanLikelihoodPlotUndo.SuspendRecording());
            if (_bivariateHeatMapPlotUndo != null) suspensions.Add(_bivariateHeatMapPlotUndo.SuspendRecording());
            if (_influenceDiagnosticsPlotUndo != null) suspensions.Add(_influenceDiagnosticsPlotUndo.SuspendRecording());

            // BA bridges are NOT suspended here — plot updates are unrelated to BA property recording.
            // BA bridges are only managed by SetupBridges/DisposeBridges lifecycle.

            return new AggregateDisposable(suspensions);
        }

        /// <summary>
        /// Rebuilds the series and annotation bridges for the specified plot.
        /// </summary>
        /// <param name="plot">The plot whose bridges need rebuilding after series/annotation changes.</param>
        /// <remarks>
        /// Call this after UpdateXxxPlot() methods that clear and repopulate
        /// <see cref="Plot.Series"/> and <see cref="Plot.Annotations"/>.
        /// Returns silently if the plot is not one of the 6 managed plots.
        /// </remarks>
        public void RebuildSeriesAndAnnotationBridges(Plot plot)
        {
            FindPlotUndoManager(plot)?.RebuildSeriesAndAnnotationBridges();
        }

        /// <summary>
        /// Finds the <see cref="PlotUndoManager"/> associated with the specified plot.
        /// </summary>
        /// <param name="plot">The plot to find the manager for.</param>
        /// <returns>The associated <see cref="PlotUndoManager"/>, or null if not found.</returns>
        private PlotUndoManager FindPlotUndoManager(Plot plot)
        {
            if (plot == _markovChainTracePlot) return _markovChainTracePlotUndo;
            if (plot == _histogramPlot) return _histogramPlotUndo;
            if (plot == _kernelDensityPlot) return _kernelDensityPlotUndo;
            if (plot == _autocorrelationPlot) return _autocorrelationPlotUndo;
            if (plot == _meanLikelihoodPlot) return _meanLikelihoodPlotUndo;
            if (plot == _bivariateHeatMapPlot) return _bivariateHeatMapPlotUndo;
            if (plot == _influenceDiagnosticsPlot) return _influenceDiagnosticsPlotUndo;
            return null;
        }

        #endregion

        #region Serialization

        /// <summary>
        /// Serializes all 7 diagnostic plot settings to the database.
        /// </summary>
        /// <param name="dtView">The database table view to write to.</param>
        /// <param name="rowIndex">The row index to write at.</param>
        /// <remarks>
        /// Uses <see cref="PlotSerializer.ToXElement"/> for modern serialization format.
        /// Called by the owning element's Save() method.
        /// </remarks>
        public void Serialize(DataTableView dtView, int rowIndex)
        {
            SerializePlot(dtView, rowIndex, "MarkovChainTracesPlotSettings", _markovChainTracePlot);
            SerializePlot(dtView, rowIndex, "HistogramPlotSettings", _histogramPlot);
            SerializePlot(dtView, rowIndex, "KernelDensityPlotSettings", _kernelDensityPlot);
            SerializePlot(dtView, rowIndex, "AutocorrelationPlotSettings", _autocorrelationPlot);
            SerializePlot(dtView, rowIndex, "MeanLikelihoodPlotSettings", _meanLikelihoodPlot);
            SerializePlot(dtView, rowIndex, "BivariatePlotSettings", _bivariateHeatMapPlot);
            SerializePlot(dtView, rowIndex, "InfluenceDiagnosticsPlotSettings", _influenceDiagnosticsPlot);

            // MCMC Report
            if (dtView.ColumnNames.Contains("MCMCReport"))
                dtView.EditCell(rowIndex, "MCMCReport", _mcmcReport ?? "");
        }

        /// <summary>
        /// Deserializes all 7 diagnostic plot settings from the database.
        /// </summary>
        /// <param name="dtView">The database table view to read from.</param>
        /// <param name="rowIndex">The row index to read at.</param>
        /// <remarks>
        /// <para>
        /// Supports backward compatibility: tries modern <see cref="PlotSerializer"/> format first,
        /// then falls back to legacy <c>OxyPlotSettingsSerializer</c> for older project files.
        /// </para>
        /// <para>
        /// Called by the owning element's Open() method. If deserialization fails for any plot,
        /// that plot retains its default factory settings.
        /// </para>
        /// </remarks>
        public void Deserialize(DataTableView dtView, int rowIndex)
        {
            DeserializePlot(dtView, rowIndex, "MarkovChainTracesPlotSettings", _markovChainTracePlot);
            DeserializePlot(dtView, rowIndex, "HistogramPlotSettings", _histogramPlot);
            DeserializePlot(dtView, rowIndex, "KernelDensityPlotSettings", _kernelDensityPlot);
            DeserializePlot(dtView, rowIndex, "AutocorrelationPlotSettings", _autocorrelationPlot);
            DeserializePlot(dtView, rowIndex, "MeanLikelihoodPlotSettings", _meanLikelihoodPlot);
            DeserializePlot(dtView, rowIndex, "BivariatePlotSettings", _bivariateHeatMapPlot);
            DeserializePlot(dtView, rowIndex, "InfluenceDiagnosticsPlotSettings", _influenceDiagnosticsPlot);

            // MCMC Report
            if (dtView.ColumnNames.Contains("MCMCReport"))
                _mcmcReport = dtView.GetCell("MCMCReport", rowIndex)?.ToString() ?? "";
        }

        /// <summary>
        /// Copies all 7 diagnostic plot settings from this instance to a target instance.
        /// </summary>
        /// <param name="target">The target <see cref="BayesianController"/> to copy to.</param>
        /// <remarks>
        /// Uses <see cref="PlotSerializer"/> round-trip (ToXElement → FromXElement) to deep-copy
        /// all visual properties. Called by the owning element's Copy() method.
        /// </remarks>
        public void CopyTo(BayesianController target)
        {
            if (target == null) return;

            CopyPlot(_markovChainTracePlot, target._markovChainTracePlot);
            CopyPlot(_histogramPlot, target._histogramPlot);
            CopyPlot(_kernelDensityPlot, target._kernelDensityPlot);
            CopyPlot(_autocorrelationPlot, target._autocorrelationPlot);
            CopyPlot(_meanLikelihoodPlot, target._meanLikelihoodPlot);
            CopyPlot(_bivariateHeatMapPlot, target._bivariateHeatMapPlot);
            CopyPlot(_influenceDiagnosticsPlot, target._influenceDiagnosticsPlot);
        }

        /// <summary>
        /// Serializes a single plot's settings to the database.
        /// </summary>
        /// <param name="dtView">The database table view to write to.</param>
        /// <param name="rowIndex">The row index to write at.</param>
        /// <param name="columnName">The database column name.</param>
        /// <param name="plot">The plot to serialize.</param>
        private static void SerializePlot(DataTableView dtView, int rowIndex, string columnName, Plot plot)
        {
            // Guard against missing columns — mirrors DeserializePlot. Lets callers with a
            // narrower schema (e.g., B17CAnalysis, which persists only 4 of the 7 Bayesian
            // diagnostic plots) safely invoke Serialize() on the whole controller.
            if (!dtView.ColumnNames.Contains(columnName)) return;
            dtView.EditCell(rowIndex, columnName, plot != null ? PlotSerializer.ToXElement(plot).ToString() : "");
        }

        /// <summary>
        /// Deserializes a single plot's settings from the database with backward compatibility.
        /// </summary>
        /// <param name="dtView">The database table view to read from.</param>
        /// <param name="rowIndex">The row index to read at.</param>
        /// <param name="columnName">The database column name.</param>
        /// <param name="plot">The target plot to apply settings to.</param>
        /// <remarks>
        /// Uses <see cref="PlotSerializer.FromXElement"/> for deserialization.
        /// Legacy OxyPlotSettingsSerializer format is handled by the v1 Open path in the owning element,
        /// so this method only needs to support the modern format.
        /// If deserialization fails, the plot retains its default factory settings.
        /// </remarks>
        private static void DeserializePlot(DataTableView dtView, int rowIndex, string columnName, Plot plot)
        {
            if (plot == null) return;
            if (!dtView.ColumnNames.Contains(columnName)) return;

            var xml = dtView.GetCell(columnName, rowIndex).ToString();
            if (string.IsNullOrEmpty(xml)) return;

            try
            {
                // Try modern PlotSerializer format first
                PlotSerializer.FromXElement(plot, XElement.Parse(xml));
            }
            catch(Exception ex) 
            {
                Debug.WriteLine($"Could not deserialize Bayesian plot settings '{columnName}': {ex.Message}");
            }
        }

        /// <summary>
        /// Deep-copies visual properties from a source plot to a target plot.
        /// </summary>
        /// <param name="source">The source plot to copy from.</param>
        /// <param name="target">The target plot to copy to.</param>
        private static void CopyPlot(Plot source, Plot target)
        {
            if (source == null || target == null) return;
            PlotSerializer.FromXElement(target, PlotSerializer.ToXElement(source));
        }

        #endregion

        #region Plot Factory Methods

        /// <summary>
        /// Applies the standard default plot style shared by all Bayesian diagnostic plots.
        /// </summary>
        /// <param name="plot">The plot to style.</param>
        /// <remarks>
        /// Sets transparent background, white plot area, dark gray legend border, and standard padding.
        /// Matches the XAML defaults from the Bayesian control templates.
        /// </remarks>
        private static void ApplyDefaultPlotStyle(Plot plot)
        {
            plot.BorderThickness = new Thickness(0);
            plot.Background = Brushes.Transparent;
            plot.LegendBackground = ColorFromHex("#8CFFFFFF");
            plot.LegendBorder = Colors.DarkGray;
            plot.LegendPosition = OxyPlot.Legends.LegendPosition.TopRight;
            plot.Padding = new Thickness(10, 10, 14, 10);
            plot.PlotAreaBackground = new SolidColorBrush(Colors.White);
        }

        /// <summary>
        /// Creates a color from a hex string.
        /// </summary>
        /// <param name="hex">The hex color string (e.g., "#8CFFFFFF").</param>
        /// <returns>The parsed <see cref="Color"/>.</returns>
        private static Color ColorFromHex(string hex)
        {
            return (Color)ColorConverter.ConvertFromString(hex);
        }

        /// <summary>
        /// Creates the default Markov chain trace plot.
        /// </summary>
        /// <returns>A new plot configured for displaying MCMC trace evolution.</returns>
        /// <remarks>
        /// Y-axis title is left empty — the App control binds it to the selected parameter name.
        /// X-axis is fixed at "Evolution" with integer formatting.
        /// Axis keys "Yaxis"/"Xaxis" match the existing XAML convention.
        /// </remarks>
        private static Plot CreateDefaultMarkovChainTracePlot()
        {
            var plot = new Plot();
            ApplyDefaultPlotStyle(plot);

            // MCMC trace plots draw 20 thin chain lines simultaneously. WPF's anti-aliased
            // stroke tessellation is the dominant render-thread cost for that many concurrent
            // line geometries; disabling it on this plot trades a barely-visible edge softness
            // for a multi-x speedup on wheel zoom, pan, and zoom-extents.
            plot.DisableShapeAntiAliasing = true;

            // Cache the rasterized plot output so the WPF compositor reuses the cached bitmap
            // while the user drags a transient overlay (e.g., the magnifier-glass zoom
            // rectangle) over the plot. Without the cache, WPF re-rasterizes the plot's
            // 20 chain geometries under the dirty region on every compositor frame during
            // the drag, producing visible multi-second drag lag. The cache regenerates on
            // every Plot.InvalidatePlot — i.e., real plot changes — so wheel/pan/zoom-extents
            // see the same fresh content.
            plot.UseBitmapCache = true;

            plot.Axes.Add(new LinearAxis
            {
                Name = "YAxis",
                Key = "Yaxis",
                Position = OxyPlot.Axes.AxisPosition.Left,
                Title = "",
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12
            });
            plot.Axes.Add(new LinearAxis
            {
                Name = "XAxis",
                Key = "Xaxis",
                Position = OxyPlot.Axes.AxisPosition.Bottom,
                Title = "Iteration",
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12,
                StringFormat = "N0"
            });

            return plot;
        }

        /// <summary>
        /// Creates the default posterior histogram plot.
        /// </summary>
        /// <returns>A new plot configured for displaying posterior parameter histograms.</returns>
        /// <remarks>
        /// Y-axis shows density with scientific notation.
        /// X-axis title is left empty — the App control binds it to the selected parameter name.
        /// </remarks>
        private static Plot CreateDefaultHistogramPlot()
        {
            var plot = new Plot();
            ApplyDefaultPlotStyle(plot);

            plot.Axes.Add(new LinearAxis
            {
                Name = "YAxis",
                Position = OxyPlot.Axes.AxisPosition.Left,
                Title = "Density",
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12,
                StringFormat = "E2"
            });
            plot.Axes.Add(new LinearAxis
            {
                Name = "XAxis",
                Position = OxyPlot.Axes.AxisPosition.Bottom,
                Title = "",
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12
            });

            return plot;
        }

        /// <summary>
        /// Creates the default kernel density estimate plot.
        /// </summary>
        /// <returns>A new plot configured for displaying smoothed posterior density curves.</returns>
        /// <remarks>
        /// Axis configuration is identical to the histogram plot.
        /// Y-axis shows density with scientific notation.
        /// X-axis title is left empty — the App control binds it to the selected parameter name.
        /// </remarks>
        private static Plot CreateDefaultKernelDensityPlot()
        {
            var plot = new Plot();
            ApplyDefaultPlotStyle(plot);

            plot.Axes.Add(new LinearAxis
            {
                Name = "YAxis",
                Position = OxyPlot.Axes.AxisPosition.Left,
                Title = "Density",
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12,
                StringFormat = "E2"
            });
            plot.Axes.Add(new LinearAxis
            {
                Name = "XAxis",
                Position = OxyPlot.Axes.AxisPosition.Bottom,
                Title = "",
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12
            });

            return plot;
        }

        /// <summary>
        /// Creates the default autocorrelation plot.
        /// </summary>
        /// <returns>A new plot configured for displaying MCMC sample autocorrelation by lag.</returns>
        /// <remarks>
        /// Y-axis shows autocorrelation values with "F2" formatting.
        /// X-axis shows lag number.
        /// Axis keys "Yaxis"/"Xaxis" match the existing XAML convention.
        /// </remarks>
        private static Plot CreateDefaultAutocorrelationPlot()
        {
            var plot = new Plot();
            ApplyDefaultPlotStyle(plot);

            plot.Axes.Add(new LinearAxis
            {
                Name = "YAxis",
                Key = "Yaxis",
                Position = OxyPlot.Axes.AxisPosition.Left,
                Title = "Autocorrelation",
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12,
                StringFormat = "F2"
            });
            plot.Axes.Add(new LinearAxis
            {
                Name = "XAxis",
                Key = "Xaxis",
                Position = OxyPlot.Axes.AxisPosition.Bottom,
                Title = "Lag",
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12
            });

            return plot;
        }

        /// <summary>
        /// Creates the default mean log-likelihood plot.
        /// </summary>
        /// <returns>A new plot configured for displaying mean log-likelihood convergence.</returns>
        /// <remarks>
        /// Y-axis is inverted (StartPosition=1, EndPosition=0) with "Mean Log-Likelihood" title.
        /// X-axis shows "Evolution" with integer formatting.
        /// This plot has no parameter combo box — it shows a single aggregated metric.
        /// </remarks>
        private static Plot CreateDefaultMeanLikelihoodPlot()
        {
            var plot = new Plot();
            ApplyDefaultPlotStyle(plot);
            plot.Title = "Mean Log-Likelihood";

            plot.Axes.Add(new LinearAxis
            {
                Name = "YAxis",
                Position = OxyPlot.Axes.AxisPosition.Left,
                Title = "Mean Log-Likelihood",
                EndPosition = 0,
                StartPosition = 1,
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12,
                StringFormat = "N0"
            });
            plot.Axes.Add(new LinearAxis
            {
                Name = "XAxis",
                Position = OxyPlot.Axes.AxisPosition.Bottom,
                Title = "Iteration",
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12,
                StringFormat = "N0"
            });

            return plot;
        }

        /// <summary>
        /// Creates the default bivariate heat map plot with color axis.
        /// </summary>
        /// <returns>A new plot configured for displaying joint posterior density as a heat map.</returns>
        /// <remarks>
        /// <para>
        /// X and Y axis titles are left empty — the App control binds them to the selected parameter names.
        /// </para>
        /// <para>
        /// Includes a <see cref="LinearColorAxis"/> on the right side with a 5-stop gradient
        /// (blue → light blue → yellow → orange → red) for density visualization,
        /// matching the existing XAML color scheme.
        /// </para>
        /// </remarks>
        private static Plot CreateDefaultBivariateHeatMapPlot()
        {
            var plot = new Plot();
            ApplyDefaultPlotStyle(plot);

            plot.Axes.Add(new LinearAxis
            {
                Name = "YAxis",
                Position = OxyPlot.Axes.AxisPosition.Left,
                Title = "",
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12,
                StringFormat = "N2"
            });
            plot.Axes.Add(new LinearAxis
            {
                Name = "XAxis",
                Position = OxyPlot.Axes.AxisPosition.Bottom,
                Title = "",
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12,
                StringFormat = "N2"
            });

            // Color axis for density gradient
            var colorAxis = new LinearColorAxis
            {
                Name = "ColorAxis",
                Position = OxyPlot.Axes.AxisPosition.Right,
                Title = "Density",
                AxisDistance = 20,
                PaletteSize = 1000,
                HighColor = Colors.Transparent,
                LowColor = Colors.Transparent,
                GradientStops = new GradientStopCollection
                {
                    new GradientStop { Color = Color.FromRgb(44, 123, 182), Offset = 0.0 },    // Blue
                    new GradientStop { Color = Color.FromRgb(171, 217, 233), Offset = 0.25 },   // Light blue
                    new GradientStop { Color = Color.FromRgb(255, 255, 191), Offset = 0.50 },   // Yellow
                    new GradientStop { Color = Color.FromRgb(253, 174, 97), Offset = 0.75 },    // Orange
                    new GradientStop { Color = Color.FromRgb(215, 25, 28), Offset = 1.0 }       // Red
                }
            };
            plot.Axes.Add(colorAxis);

            return plot;
        }

        /// <summary>
        /// Creates the default influence diagnostics tornado plot.
        /// </summary>
        /// <returns>A new plot configured for displaying influence diagnostics as a tornado chart.</returns>
        /// <remarks>
        /// <para>
        /// Uses a <see cref="CategoryAxis"/> on the left (Y-axis) for observation/component labels
        /// and a <see cref="LinearAxis"/> on the bottom (X-axis) for the influence metric value.
        /// </para>
        /// <para>
        /// The App control dynamically switches axis titles and populates series based on the
        /// selected view (Observation Influence, Prior Influence, or Combined Influence).
        /// </para>
        /// </remarks>
        private static Plot CreateDefaultInfluenceDiagnosticsPlot()
        {
            var plot = new Plot();
            ApplyDefaultPlotStyle(plot);

            plot.Axes.Add(new CategoryAxis
            {
                Name = "YAxis",
                Position = OxyPlot.Axes.AxisPosition.Left,
                Title = "",
                GapWidth = 0.5,
                TitleFontSize = 16,
                FontSize = 11
            });
            plot.Axes.Add(new LinearAxis
            {
                Name = "XAxis",
                Position = OxyPlot.Axes.AxisPosition.Bottom,
                Title = "Pareto k",
                AxisTitleDistance = 20,
                TitleFontSize = 16,
                FontSize = 12
            });

            return plot;
        }

        #endregion

        #region IDisposable

        /// <summary>
        /// Releases all undo bridges managed by this instance.
        /// </summary>
        public void Dispose()
        {
            if (_isDisposed) return;
            _isDisposed = true;
            DisposeBridges();
        }

        #endregion

        #region BayesianAnalysis Undo Bridges

        /// <summary>
        /// Creates the three BayesianAnalysis undo bridges and subscribes to UseDefaults flag changes.
        /// </summary>
        /// <param name="ba">The <see cref="BayesianAnalysis"/> to bridge. May be null.</param>
        private void SetupBayesianBridges(BayesianAnalysis ba)
        {
            DisposeBayesianBridges();
            _subscribedBayesianAnalysis = ba;
            if (ba == null || _getUndo == null) return;

            // Always-record bridge: UseDefaults flags, Type, PointEstimator, CredibleIntervalWidth, OutputLength
            _bayesianAlwaysBridge = new UndoableStateBridge(
                ba, _getUndo, "Bayesian settings", _target,
                includedProperties: AlwaysRecordProperties,
                onActionRecorded: _onRecorded);

            // Simulation properties bridge — always alive to preserve baselines.
            // The getUndo lambda returns null when UseDefaults is true, so the bridge
            // tracks property changes internally but cannot push to the undo manager.
            _simulationUndoEnabled = !ba.UseSimulationDefaults;
            _simulationPropsBridge = new UndoableStateBridge(
                ba, () => _simulationUndoEnabled ? _getUndo() : null,
                "simulation options", _target,
                includedProperties: SimulationDefaultsProperties,
                onActionRecorded: _onRecorded);

            // Advanced properties bridge — same gating pattern.
            _advancedUndoEnabled = !ba.UseAdvancedSimulationDefaults;
            _advancedPropsBridge = new UndoableStateBridge(
                ba, () => _advancedUndoEnabled ? _getUndo() : null,
                "advanced simulation options", _target,
                includedProperties: AdvancedDefaultsProperties,
                onActionRecorded: _onRecorded);

            // Listen for UseDefaults flag changes to toggle the gating flags
            ba.PropertyChanged += BayesianAnalysis_UseDefaultsChanged;

        }

        /// <summary>
        /// Disposes all BayesianAnalysis bridges and unsubscribes from UseDefaults monitoring.
        /// </summary>
        private void DisposeBayesianBridges()
        {
            if (_subscribedBayesianAnalysis != null)
                _subscribedBayesianAnalysis.PropertyChanged -= BayesianAnalysis_UseDefaultsChanged;

            _bayesianAlwaysBridge?.Dispose();
            _bayesianAlwaysBridge = null;
            _simulationPropsBridge?.Dispose();
            _simulationPropsBridge = null;
            _advancedPropsBridge?.Dispose();
            _advancedPropsBridge = null;

            _subscribedBayesianAnalysis = null;
        }

        /// <summary>
        /// Handles UseDefaults flag changes to create or dispose the conditional simulation bridges.
        /// When UseDefaults goes true, the bridge is disposed so automatic property changes from
        /// <see cref="BayesianAnalysis.SetDefaultSimulationOptions"/> are NOT recorded.
        /// When UseDefaults goes false, a new bridge is created to record user edits.
        /// Also calls <see cref="_onValidate"/> for validation refresh on any BA property change.
        /// </summary>
        private void BayesianAnalysis_UseDefaultsChanged(object sender, PropertyChangedEventArgs e)
        {
            var ba = _subscribedBayesianAnalysis;
            if (ba == null) return;

            // Refresh validation on any BA property change (including during undo)
            _onValidate?.Invoke();

            if (e.PropertyName == nameof(BayesianAnalysis.UseSimulationDefaults))
            {
                _simulationUndoEnabled = !ba.UseSimulationDefaults;
            }
            else if (e.PropertyName == nameof(BayesianAnalysis.UseAdvancedSimulationDefaults))
            {
                _advancedUndoEnabled = !ba.UseAdvancedSimulationDefaults;
            }
        }

        #endregion

        #region Report Management

        /// <summary>
        /// Updates the cached MCMC report by calling <see cref="BayesianAnalysis.GenerateReport()"/>.
        /// </summary>
        /// <param name="ba">The <see cref="BayesianAnalysis"/> to generate the report from.</param>
        public void UpdateReport(BayesianAnalysis ba)
        {
            _mcmcReport = ba?.GenerateReport() ?? string.Empty;
        }

        #endregion
    }
}
