"""Generate the report's complete method index and source-inventory figure.

The catalog owns scientific dispositions and acceptance rules. This script only
projects that data into the publication; it never executes tests or upgrades an
evidence status. Run validate-verification-catalog.ps1 -RequireComplete first to
check the catalog against the current C# declarations.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from html import escape
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs" / "verification" / "report"
GROUPS = [
    ("ModelEstimation/", "Estimation and diagnostics", "estimation-diagnostics.md"),
    ("DistributionFitting/", "Distribution fitting", "data-distributions-b17c.md"),
    ("Univariate/ValidationTests/", "Univariate recovery", "data-distributions-b17c.md"),
    ("Univariate/VerificationReportTests/", "Published univariate comparisons", "data-distributions-b17c.md"),
    ("Univariate/Bulletin17CTests/", "Bulletin 17C", "data-distributions-b17c.md"),
    ("Univariate/PointProcess", "Point process", "point-process-analysis.md"),
    ("Univariate/CompetingRisk", "Competing risks", "competing-risk-analysis.md"),
    ("Univariate/Mixture", "Mixtures", "mixture-analysis.md"),
    ("Univariate/Composite", "Composite analyses", "composite-analysis.md"),
    ("Bivariate/", "Bivariate and coincident frequency", "bivariate-analyses.md"),
    ("RatingCurve/", "Rating curves", "rating-curve.md"),
    ("TimeSeries", "Time-series models", "time-series-analyses.md"),
    ("SpatialExtremes/", "Spatial extremes", "spatial-extremes.md"),
]
KINDS = {
    "analytical": "Analytical",
    "independent": "Independent calculation",
    "external-package": "External package",
    "published-source": "Published source",
    "recovery": "Recovery",
}
STATUSES = {"verified": "Verified", "accepted-limitation": "Accepted limitation"}
LIMITATIONS = {
    "SampleFromPriors_SoftJointPrior_CurrentlyDrawsIndependentMarginals":
        "The generic sampler draws independent marginal priors and does not sample the additional soft joint-prior coupling.",
    "GmmObservationInfluence_CurrentMagnitudeDiffersFromExactDeletionScale":
        "The GMM one-step influence magnitude is not calibrated to exact deletion scale; the tested outlier-ranking result remains valid.",
}


def group_for(entry: dict) -> tuple[str, str, str]:
    """Require every method to have one explicit publication chapter owner."""
    relative = entry["source"].split("src/RMC.BestFit.Verification/", 1)[1]
    matches = [group for group in GROUPS if relative.startswith(group[0])]
    if len(matches) != 1:
        raise ValueError(f"Expected one publication owner for {entry['source']}: {matches}")
    return matches[0]


def md(value: str) -> str:
    """Escape a plain catalog field for a Markdown table cell."""
    return value.replace("|", "\\|").replace("\n", " ").strip()


def generate_index(entries: list[dict], retired: list[dict], date: str) -> str:
    """Produce one row per method, grouped into readable source-class sections."""
    grouped: dict[str, list[dict]] = defaultdict(list)
    identities = set()
    for entry in entries:
        identity = (entry["namespace"], entry["class"], entry["method"])
        if identity in identities:
            raise ValueError(f"Duplicate method: {identity}")
        identities.add(identity)
        grouped[group_for(entry)[1]].append(entry)
        if entry["status"] not in STATUSES or entry["primaryEvidenceKind"] not in KINDS:
            raise ValueError(f"Unmapped scientific disposition or evidence kind: {identity}")
    statuses = Counter(e["status"] for e in entries)
    classes = {(e["namespace"], e["class"]) for e in entries}
    lines = [
        "<!-- verification-status: publication-draft -->",
        "<!-- Generated by scripts/build-verification-coverage.py; do not edit manually. -->",
        "", "# Appendix A. Complete Verification Test Index", "",
        f"The source inventory audited on {date} contains **{len(entries)} methods in {len(classes)} active test classes**. "
        "Every executable verification method appears exactly once below; helper methods are not counted as tests.", "",
        f"The catalog records {statuses['verified']} methods as verified and {statuses['accepted-limitation']} as accepted limitations. "
        "**Verified** identifies a check with a declared oracle, acceptance rule, and verified catalog disposition. "
        "Acceptance rules, sample sizes, seeds, oracle descriptions, artifact paths, and original evidence-ledger anchors remain in the "
        "[machine-readable catalog](../verification-catalog.json). The PDF embeds the current catalog as an attachment; its repository links identify the source-review baseline. Each method links to the source file containing its assertions, including partial classes.", "",
        "| Report area | Active classes | Methods |", "|---|---:|---:|",
    ]
    for _, title, chapter in GROUPS:
        rows = grouped[title]
        lines.append(f"| [{title}]({chapter}) | {len({(e['namespace'], e['class']) for e in rows})} | {len(rows)} |")
    lines += [f"| **Total** | **{len(classes)}** | **{len(entries)}** |", ""]
    for _, title, chapter in GROUPS:
        lines += [f"## {title}", "", f"Interpretation and results: [{title}]({chapter}).", ""]
        by_class: dict[tuple[str, str], list[dict]] = defaultdict(list)
        for entry in grouped[title]:
            by_class[(entry["namespace"], entry["class"])].append(entry)
        for (namespace, name), rows in sorted(by_class.items()):
            sources = sorted({row["source"] for row in rows})
            source_links = ", ".join(f"[{Path(source).name}](../../../{source})" for source in sources)
            models = "; ".join(sorted({e["model"] for e in rows}))
            lines += [f"### {name}", "", f"Source: {source_links}. Namespace: `{namespace}`.", "",
                      f"Scope: {models}.", "", "| Method | Evidence | Disposition |", "|---|---|---|"]
            for entry in sorted(rows, key=lambda row: row["method"]):
                lines.append(f"| [`{entry['method']}`](../../../{entry['source']}) | {KINDS[entry['primaryEvidenceKind']]} | {STATUSES[entry['status']]} |")
            limitations = [e for e in rows if e["status"] == "accepted-limitation"]
            for entry in limitations:
                lines += ["", f"Limitation: {LIMITATIONS[entry['method']]}"]
            lines += [""]
    return "\n".join(lines).rstrip() + "\n"


def generate_figure(entries: list[dict]) -> str:
    """Draw a vector inventory chart; counts are not pass rates or coverage rates."""
    counts = Counter(group_for(entry)[1] for entry in entries)
    height = 125 + 38 * len(GROUPS)
    lines = [f'<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="{height}" viewBox="0 0 1000 {height}" role="img" aria-labelledby="title description">',
             '<title id="title">Current verification methods by report area</title>',
             f'<desc id="description">{len(entries)} methods. Counts describe the active source inventory, not new test executions or interval coverage.</desc>',
             f'<rect width="1000" height="{height}" fill="white"/>',
             '<text x="25" y="34" fill="#15324b" font-family="Arial,sans-serif" font-size="24" font-weight="700">Current verification methods by report area</text>',
             f'<text x="25" y="61" fill="#60717f" font-family="Arial,sans-serif" font-size="14">{len(entries)} methods; test identities and evidence dispositions are listed in Appendix A.</text>']
    for i, (_, title, _) in enumerate(GROUPS):
        y = 90 + 38 * i
        width = counts[title] / max(counts.values()) * 580
        lines += [f'<text x="300" y="{y+17}" text-anchor="end" fill="#15324b" font-family="Arial,sans-serif" font-size="15">{escape(title)}</text>',
                  f'<rect x="318" y="{y}" width="{width:.1f}" height="25" rx="3" fill="#28648b"/>',
                  f'<text x="{330+width:.1f}" y="{y+18}" fill="#15324b" font-family="Arial,sans-serif" font-size="16" font-weight="700">{counts[title]}</text>']
    lines += ["</svg>"]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Write the controlled projections, or fail when checked copies have drifted."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate generated files without changing them.")
    args = parser.parse_args()
    catalog_root = ROOT / "docs" / "verification"
    entries = json.loads((catalog_root / "verification-catalog.json").read_text(encoding="utf-8"))["entries"]
    retired = json.loads((catalog_root / "verification-catalog-retired.json").read_text(encoding="utf-8"))["entries"]
    metadata = json.loads((ROOT / "docs" / "report-metadata.json").read_text(encoding="utf-8"))
    date = metadata["verification_report"]["checkpoint"]["publication_date_display"]
    outputs = {
        REPORT / "test-coverage.md": generate_index(entries, retired, date),
        REPORT / "figures" / "verification-cell-summary.svg": generate_figure(entries),
    }
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Generated report content is stale: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    print(f"{'Checked' if args.check else 'Generated'} complete index: {len(entries)} active methods, {len(retired)} retired records.")


if __name__ == "__main__":
    main()
