using System.Text.Json;
using Numerics.Data;
using RMC.BestFit.Models;

namespace RMC.BestFit.Verification.Univariate.PointProcessTests;

/// <summary>
/// Verifies the stationary point-process parameterization against a frozen SciPy oracle.
/// </summary>
/// <remarks>
/// The artifact was generated by Python 3.12.13, NumPy 2.5.2, and SciPy 1.17.1.
/// SciPy uses Coles generalized-Pareto shape <c>xi</c>, while Numerics uses Hosking
/// <c>Kappa = -xi</c>. SciPy's univariate distributions do not support the production
/// two-season exposure likelihood, so this class makes no seasonal package-parity claim.
/// </remarks>
[TestClass]
public class PointProcessExternalPackageOracleTests
{
    private const string ArtifactFileName = "stationary-poisson-gpa-scipy-oracle.json";

    /// <summary>
    /// Verifies stationary threshold intensity, exact-event likelihood, conditional tail, and
    /// annual-maximum response against SciPy's Poisson, generalized-Pareto, and GEV values.
    /// </summary>
    [TestMethod]
    public void StationaryPoissonGpa_MatchesSciPyArtifact()
    {
        using JsonDocument document = LoadArtifact();
        JsonElement inputs = document.RootElement.GetProperty("inputs");
        JsonElement expected = document.RootElement.GetProperty("expected");
        double location = inputs.GetProperty("location").GetDouble();
        double scale = inputs.GetProperty("scale").GetDouble();
        double kappa = inputs.GetProperty("numericsKappa").GetDouble();
        double threshold = inputs.GetProperty("threshold").GetDouble();
        double exposureYears = inputs.GetProperty("exposureYears").GetDouble();
        double[] exactValues = inputs.GetProperty("exactValues")
            .EnumerateArray()
            .Select(value => value.GetDouble())
            .ToArray();

        var observations = exactValues
            .Select((value, index) => new ExactData(new DateTime(2000, 1, 1).AddDays(index), value))
            .ToList();
        var frame = new DataFrame
        {
            ExactSeries = new ExactSeries(observations),
            PointProcessObservationYears = exposureYears
        };
        var model = new PointProcessModel { UseDefaults = false, DataFrame = frame };
        model.Threshold = threshold;
        model.TotalYears = exposureYears;
        model.SetDefaultParameters();
        double[] parameters = { location, scale, kappa };
        model.SetParameterValues(parameters);
        var distribution = model.Distribution;
        Assert.IsNotNull(distribution, "The stationary point-process model did not configure its GEV distribution.");

        AssertScaledEqual(
            expected.GetProperty("thresholdIntensity").GetDouble(),
            model.FittedThresholdIntensity,
            "Annual threshold intensity");
        AssertScaledEqual(
            expected.GetProperty("pointProcessLogLikelihood").GetDouble(),
            model.DataLogLikelihood(parameters),
            "Stationary exact-event point-process log likelihood");

        double tailValue = inputs.GetProperty("tailValue").GetDouble();
        double tailIntensity = -Math.Log(distribution.Distributions.First().CDF(tailValue));
        double conditionalSurvival = tailIntensity / model.FittedThresholdIntensity;
        AssertScaledEqual(
            expected.GetProperty("conditionalSurvivalAtTailValue").GetDouble(),
            conditionalSurvival,
            "Conditional generalized-Pareto survival");

        double annualProbability = inputs.GetProperty("annualMaximumProbability").GetDouble();
        AssertScaledEqual(
            expected.GetProperty("annualMaximumQuantile").GetDouble(),
            distribution.InverseCDF(annualProbability),
            "Annual-maximum quantile");
    }

    /// <summary>Loads the frozen SciPy artifact from the test output directory.</summary>
    /// <returns>The parsed JSON document.</returns>
    private static JsonDocument LoadArtifact()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "VerificationData", ArtifactFileName);
        Assert.IsTrue(File.Exists(path), $"Missing point-process SciPy artifact: {path}");
        return JsonDocument.Parse(File.ReadAllText(path));
    }

    /// <summary>Compares one deterministic external value at a scaled 1e-12 tolerance.</summary>
    /// <param name="expected">Frozen SciPy value.</param>
    /// <param name="actual">Production value.</param>
    /// <param name="label">Quantity label.</param>
    private static void AssertScaledEqual(double expected, double actual, string label)
    {
        double tolerance = 1E-12 * Math.Max(1.0, Math.Abs(expected));
        Assert.AreEqual(expected, actual, tolerance, $"{label} disagreed with the frozen SciPy value.");
    }
}
