using Numerics.Data.Statistics;
using Numerics.Distributions;
using RMC.BestFit.Analyses;
using RMC.BestFit.Estimation;
using RMC.BestFit.Models;
using RMC.BestFit.Verification.Recovery;
using BestFitDataFrame = RMC.BestFit.Models.DataFrame;

namespace RMC.BestFit.Verification.Univariate.MixtureTests;

/// <summary>
/// Generated-parent recovery verification for finite Normal mixtures.
/// </summary>
/// <remarks>
/// Every fixture contains 1,000 scalar observations generated with seed 12345. Continuous
/// components are identified by ascending mean; Bayesian draws reconstruct full-K physical weights
/// from the sampled K-1 coordinates before ordering. Frequentist cells use responsibility-count
/// weight variance and observed-likelihood component covariance with absolute standardized error
/// no greater than 1.96. Bayesian cells use sampler seeds 22345, 32345, or 42345 and require central
/// 95% inclusion, R-hat below 1.10, and ESS of at least 100. The zero-inflated cells treat the atom
/// and positive-conditioned continuous simplex as distinct identified components.
/// </remarks>
[TestClass]
public class MixtureRecoveryTests
{
    /// <summary>
    /// Sample size for synthetic mixture generation and recovery.
    /// </summary>
    private const int SampleSize = 1000;

    /// <summary>
    /// Verifies generated-parent recovery for a two-component Normal mixture.
    /// </summary>
    [TestMethod]
    public void NormalMixture2D_Recovery_Parity()
    {
        VerifyRecovery(
            generatingWeights: new[] { 0.3, 0.7 },
            generatingDistributions: new[]
            {
                new Normal(0.0, 1.0),
                new Normal(3.0, 0.1)
            },
            isZeroInflated: false,
            zeroWeight: 0.0);
    }

    /// <summary>
    /// Verifies generated-parent recovery for a zero-inflated two-component Normal hurdle mixture.
    /// </summary>
    [TestMethod]
    public void ZeroInflatedNormalMixture2D_Recovery_Parity()
    {
        VerifyRecovery(
            generatingWeights: new[] { 0.3, 0.6 },
            generatingDistributions: new[]
            {
                new Normal(3.0, 0.1),
                new Normal(5.0, 2.0)
            },
            isZeroInflated: true,
            zeroWeight: 0.1);
    }

    /// <summary>
    /// Verifies generated-parent recovery for a three-component Normal mixture.
    /// </summary>
    [TestMethod]
    public void NormalMixture3D_Recovery_Parity()
    {
        VerifyRecovery(
            generatingWeights: new[] { 0.2, 0.3, 0.5 },
            generatingDistributions: new[]
            {
                new Normal(0.0, 1.0),
                new Normal(3.0, 0.1),
                new Normal(5.0, 2.0)
            },
            isZeroInflated: false,
            zeroWeight: 0.0);
    }

    /// <summary>
    /// Verifies Bayesian recovery of a two-component Normal mixture generated by BestFit.
    /// </summary>
    /// <returns>A task representing the asynchronous Bayesian analysis.</returns>
    [TestMethod]
    public async Task NormalMixture2D_BayesianRecovery()
    {
        await VerifyBayesianRecoveryAsync(
            generatingWeights: new[] { 0.3, 0.7 },
            generatingDistributions: new[]
            {
                new Normal(0.0, 1.0),
                new Normal(3.0, 0.1)
            },
            isZeroInflated: false,
            zeroWeight: 0.0,
            samplerSeed: 22345);
    }

    /// <summary>
    /// Verifies Bayesian recovery of a zero-inflated two-component Normal hurdle mixture generated by BestFit.
    /// </summary>
    /// <returns>A task representing the asynchronous Bayesian analysis.</returns>
    [TestMethod]
    public async Task ZeroInflatedNormalMixture2D_BayesianRecovery()
    {
        await VerifyBayesianRecoveryAsync(
            generatingWeights: new[] { 0.3, 0.6 },
            generatingDistributions: new[]
            {
                new Normal(3.0, 0.1),
                new Normal(5.0, 2.0)
            },
            isZeroInflated: true,
            zeroWeight: 0.1,
            samplerSeed: 32345);
    }

    /// <summary>
    /// Verifies Bayesian recovery of a three-component Normal mixture generated by BestFit.
    /// </summary>
    /// <returns>A task representing the asynchronous Bayesian analysis.</returns>
    [TestMethod]
    public async Task NormalMixture3D_BayesianRecovery()
    {
        await VerifyBayesianRecoveryAsync(
            generatingWeights: new[] { 0.2, 0.3, 0.5 },
            generatingDistributions: new[]
            {
                new Normal(0.0, 1.0),
                new Normal(3.0, 0.1),
                new Normal(5.0, 2.0)
            },
            isZeroInflated: false,
            zeroWeight: 0.0,
            samplerSeed: 42345);
    }

    /// <summary>
    /// Generates one sample, validates the parameterization crosswalk, and applies the common frequentist recovery rule.
    /// </summary>
    /// <param name="generatingWeights">The physical component weights.</param>
    /// <param name="generatingDistributions">The generating Normal components.</param>
    /// <param name="isZeroInflated">Whether to generate and fit a positive-hurdle mixture.</param>
    /// <param name="zeroWeight">The generating atom probability.</param>
    private static void VerifyRecovery(
        double[] generatingWeights,
        Normal[] generatingDistributions,
        bool isZeroInflated,
        double zeroWeight)
    {
        MixtureModel generator = CreateGeneratingModel(
            generatingWeights,
            generatingDistributions,
            isZeroInflated,
            zeroWeight);
        double[] sample = generator.GenerateRandomValues(SampleSize, 12345);
        Assert.AreEqual(
            SampleSize,
            sample.Length,
            "The BestFit mixture generator did not return the requested sample size.");
        BestFitDataFrame dataFrame = CreateDataFrame(sample);
        var distributionTypes = Enumerable
            .Repeat(UnivariateDistributionType.Normal, generatingDistributions.Length)
            .ToList();
        var bestFit = new MixtureModel(dataFrame, distributionTypes, isZeroInflated);

        AssertRecoveryCrosswalk(
            bestFit,
            generatingWeights,
            generatingDistributions,
            isZeroInflated,
            zeroWeight);
        bestFit.ExpectationMaximization(
            out double[] bestFitParameters,
            out double[,] covariance,
            out _);
        Mixture bestFitFit = ReconstructBestFitMixture(bestFit, bestFitParameters);
        AssertFrequentistRecovery(
            generatingWeights,
            generatingDistributions,
            bestFit,
            bestFitFit,
            covariance);
        AssertZeroAtomRecovery(bestFit, isZeroInflated, zeroWeight);
    }

    /// <summary>
    /// Verifies the declared full-K/K-1, prior-support, label, and likelihood crosswalk before fitting.
    /// </summary>
    /// <param name="model">The fresh fitted model.</param>
    /// <param name="generatingWeights">The generating physical component weights.</param>
    /// <param name="generatingDistributions">The generating Normal components.</param>
    /// <param name="isZeroInflated">Whether the fixture contains a zero atom.</param>
    /// <param name="zeroWeight">The generating zero-atom probability.</param>
    private static void AssertRecoveryCrosswalk(
        MixtureModel model,
        double[] generatingWeights,
        IReadOnlyList<Normal> generatingDistributions,
        bool isZeroInflated,
        double zeroWeight)
    {
        Assert.AreEqual(isZeroInflated, model.IsZeroInflated, "Zero-inflation convention changed.");
        Assert.AreEqual(generatingDistributions.Count, model.Mixture!.Distributions.Length,
            "Mixture component count changed.");
        Assert.IsTrue(
            generatingDistributions.Select(distribution => distribution.Mean).SequenceEqual(
                generatingDistributions.Select(distribution => distribution.Mean).OrderBy(value => value)),
            "The predeclared component labels must be ordered by strictly separated means.");

        double[] fittedCoordinateWeights = GetFittedCoordinateWeights(model, generatingWeights);
        double[] parentParameters = CreateBestFitParameters(
            fittedCoordinateWeights,
            generatingDistributions);
        Assert.IsTrue(double.IsFinite(model.PriorLogLikelihood(parentParameters)),
            "The generating physical coordinates must lie inside every configured prior.");
        double parentLogLikelihood = model.DataLogLikelihood(parentParameters);
        double[] collapsedParameters = model.Parameters.Select(parameter => parameter.Value).ToArray();
        double collapsedLogLikelihood = model.DataLogLikelihood(collapsedParameters);
        Assert.IsTrue(
            double.IsFinite(parentLogLikelihood) && parentLogLikelihood > collapsedLogLikelihood,
            $"Parent log likelihood {parentLogLikelihood:G17} must beat the fresh collapsed/default alternative {collapsedLogLikelihood:G17}.");

        if (isZeroInflated)
        {
            Assert.AreEqual(1.0, zeroWeight + generatingWeights.Sum(), 1E-12,
                "Generating zero and continuous physical weights must sum to one.");
        }
        else
        {
            Assert.AreEqual(1.0, generatingWeights.Sum(), 1E-12,
                "Generating physical weights must sum to one.");
        }
    }

    /// <summary>
    /// Applies the central-95% standardized-error rule using the production EM covariance.
    /// </summary>
    /// <param name="generatingWeights">The generating physical weights.</param>
    /// <param name="generatingDistributions">The generating Normal components.</param>
    /// <param name="model">The fitted model that defines the observed zero-atom mass.</param>
    /// <param name="fittedMixture">The reconstructed full-K EM fit.</param>
    /// <param name="covariance">The full-K EM covariance.</param>
    private static void AssertFrequentistRecovery(
        double[] generatingWeights,
        IReadOnlyList<Normal> generatingDistributions,
        MixtureModel model,
        Mixture fittedMixture,
        double[,] covariance)
    {
        int componentCount = generatingDistributions.Count;
        double[] fittedCoordinateWeights = GetFittedCoordinateWeights(model, generatingWeights);
        var expected = fittedCoordinateWeights
            .Select((weight, index) => (
                Weight: weight,
                Parameters: generatingDistributions[index].GetParameters))
            .OrderBy(component => component.Parameters[0])
            .ToArray();
        var actual = SortByComponentMeanWithIndex(fittedMixture);
        Assert.AreEqual(componentCount * 3, covariance.GetLength(0),
            "The full-K EM covariance row count changed.");
        Assert.AreEqual(componentCount * 3, covariance.GetLength(1),
            "The full-K EM covariance column count changed.");

        for (int componentIndex = 0; componentIndex < componentCount; componentIndex++)
        {
            int originalIndex = actual[componentIndex].OriginalIndex;
            RecoveryAcceptance.AssertFrequentistStandardizedError(
                $"ordered component {componentIndex + 1} weight",
                actual[componentIndex].Weight,
                expected[componentIndex].Weight,
                Math.Sqrt(covariance[originalIndex, originalIndex]));

            for (int parameterIndex = 0; parameterIndex < 2; parameterIndex++)
            {
                int covarianceIndex = componentCount + 2 * originalIndex + parameterIndex;
                string parameterName = parameterIndex == 0 ? "mean" : "standard deviation";
                RecoveryAcceptance.AssertFrequentistStandardizedError(
                    $"ordered component {componentIndex + 1} {parameterName}",
                    actual[componentIndex].Parameters[parameterIndex],
                    expected[componentIndex].Parameters[parameterIndex],
                    Math.Sqrt(covariance[covarianceIndex, covarianceIndex]));
            }
        }
    }

    /// <summary>
    /// Applies the N=1000 binomial standardized-error rule to the separately identified zero atom.
    /// </summary>
    /// <param name="model">The fitted model.</param>
    /// <param name="isZeroInflated">Whether the fixture contains a zero atom.</param>
    /// <param name="zeroWeight">The generating atom probability.</param>
    private static void AssertZeroAtomRecovery(
        MixtureModel model,
        bool isZeroInflated,
        double zeroWeight)
    {
        if (!isZeroInflated)
            return;

        double standardError = Math.Sqrt(zeroWeight * (1.0 - zeroWeight) / SampleSize);
        RecoveryAcceptance.AssertFrequentistStandardizedError(
            "zero-atom probability",
            model.Mixture!.ZeroWeight,
            zeroWeight,
            standardError);
    }

    /// <summary>
    /// Generates a known parent sample through BestFit, fits it through <see cref="MixtureAnalysis"/>,
    /// and verifies Bayesian parameter recovery and chain diagnostics.
    /// </summary>
    /// <param name="generatingWeights">The physical component weights.</param>
    /// <param name="generatingDistributions">The generating Normal components.</param>
    /// <param name="isZeroInflated">Whether to generate and fit a positive-hurdle mixture.</param>
    /// <param name="zeroWeight">The generating atom probability.</param>
    /// <param name="samplerSeed">The deterministic MCMC seed.</param>
    /// <returns>A task representing the asynchronous Bayesian analysis.</returns>
    private static async Task VerifyBayesianRecoveryAsync(
        double[] generatingWeights,
        Normal[] generatingDistributions,
        bool isZeroInflated,
        double zeroWeight,
        int samplerSeed)
    {
        MixtureModel generator = CreateGeneratingModel(
            generatingWeights,
            generatingDistributions,
            isZeroInflated,
            zeroWeight);
        double[] sample = generator.GenerateRandomValues(SampleSize, 12345);
        Assert.AreEqual(
            SampleSize,
            sample.Length,
            "The BestFit mixture generator did not return the requested sample size.");

        BestFitDataFrame dataFrame = CreateDataFrame(sample);
        var distributionTypes = Enumerable
            .Repeat(UnivariateDistributionType.Normal, generatingDistributions.Length)
            .ToList();
        var model = new MixtureModel(dataFrame, distributionTypes, isZeroInflated);
        AssertRecoveryCrosswalk(
            model,
            generatingWeights,
            generatingDistributions,
            isZeroInflated,
            zeroWeight);
        MixtureAnalysis analysis = ConfigureBayesianAnalysis(model, samplerSeed);
        Exception? analysisError = null;
        analysis.AnalysisCompleted += (_, args) => analysisError = args.Error;

        var validation = analysis.Validate();
        Assert.IsTrue(validation.IsValid, string.Join(Environment.NewLine, validation.ValidationMessages));

        await analysis.RunAsync();

        Assert.IsTrue(
            analysis.IsEstimated,
            $"Bayesian mixture recovery did not complete. {analysisError ?? analysis.BayesianAnalysis.LastError}");
        Assert.IsNotNull(analysis.BayesianAnalysis.Results, "Bayesian mixture results are null.");

        AssertZeroAtomRecovery(model, isZeroInflated, zeroWeight);
        AssertBayesianPhysicalRecovery(
            generatingWeights,
            generatingDistributions,
            model,
            analysis);
        AssertBayesianDiagnostics(model, analysis);
    }

    /// <summary>
    /// Configures the shared Bayesian recovery analysis with the default DEMCzs simulation settings.
    /// </summary>
    /// <param name="model">The mixture model to estimate.</param>
    /// <param name="seed">The deterministic sampler seed.</param>
    /// <returns>A configured Bayesian mixture analysis.</returns>
    private static MixtureAnalysis ConfigureBayesianAnalysis(MixtureModel model, int seed)
    {
        var analysis = new MixtureAnalysis(model);
        analysis.BayesianAnalysis.PRNGSeed = seed;
        return analysis;
    }

    /// <summary>
    /// Verifies central-95% posterior intervals after reconstructing physical weights and ordering each draw by mean.
    /// </summary>
    /// <param name="generatingWeights">The true physical component weights.</param>
    /// <param name="generatingDistributions">The true Normal components.</param>
    /// <param name="model">The fitted BestFit mixture model.</param>
    /// <param name="analysis">The completed Bayesian mixture analysis.</param>
    private static void AssertBayesianPhysicalRecovery(
        double[] generatingWeights,
        IReadOnlyList<Normal> generatingDistributions,
        MixtureModel model,
        MixtureAnalysis analysis)
    {
        double[] fittedCoordinateWeights = GetFittedCoordinateWeights(model, generatingWeights);
        var expected = fittedCoordinateWeights
            .Select((weight, index) => (
                Weight: weight,
                Parameters: generatingDistributions[index].GetParameters))
            .OrderBy(component => component.Parameters[0])
            .ToArray();
        int componentCount = expected.Length;
        double componentMass = model.IsZeroInflated ? 1.0 - model.Mixture!.ZeroWeight : 1.0;
        var orderedDraws = analysis.BayesianAnalysis.Results!.Output
            .Select(output => ExpandAndSortDraw(output.Values, componentCount, componentMass))
            .ToArray();

        Assert.IsTrue(orderedDraws.Length > 0, "Bayesian mixture output is empty.");
        for (int componentIndex = 0; componentIndex < expected.Length; componentIndex++)
        {
            double[] weightDraws = orderedDraws
                .Select(draw => draw[componentIndex].Weight)
                .ToArray();
            Assert.IsTrue(weightDraws.All(double.IsFinite),
                $"Ordered component {componentIndex + 1} physical-weight draws must be finite.");
            Array.Sort(weightDraws);
            RecoveryAcceptance.AssertFrequentistParentInInterval(
                $"ordered component {componentIndex + 1} weight",
                expected[componentIndex].Weight,
                Statistics.Percentile(weightDraws, 0.025d, true),
                Statistics.Percentile(weightDraws, 0.975d, true));

            for (int parameterIndex = 0;
                 parameterIndex < expected[componentIndex].Parameters.Length;
                 parameterIndex++)
            {
                double[] coordinateDraws = orderedDraws
                    .Select(draw => draw[componentIndex].Parameters[parameterIndex])
                    .ToArray();
                string parameterName = parameterIndex == 0 ? "mean" : "standard deviation";
                Assert.IsTrue(coordinateDraws.All(double.IsFinite),
                    $"Ordered component {componentIndex + 1} {parameterName} draws must be finite.");
                Array.Sort(coordinateDraws);
                RecoveryAcceptance.AssertFrequentistParentInInterval(
                    $"ordered component {componentIndex + 1} {parameterName}",
                    expected[componentIndex].Parameters[parameterIndex],
                    Statistics.Percentile(coordinateDraws, 0.025d, true),
                    Statistics.Percentile(coordinateDraws, 0.975d, true));
            }
        }
    }

    /// <summary>
    /// Verifies split R-hat and conservative effective sample size for every sampled mixture parameter.
    /// </summary>
    /// <param name="model">The fitted mixture model.</param>
    /// <param name="analysis">The completed Bayesian analysis.</param>
    private static void AssertBayesianDiagnostics(MixtureModel model, MixtureAnalysis analysis)
    {
        var parameterResults = analysis.BayesianAnalysis.Results!.ParameterResults;
        int derivedWeightIndex = model.Mixture!.Distributions!.Length - 1;
        int sampledParameterCount = model.NumberOfParameters - 1;
        Assert.AreEqual(sampledParameterCount, parameterResults.Length, "MCMC sampled diagnostic parameter count mismatch.");
        for (int parameterIndex = 0; parameterIndex < parameterResults.Length; parameterIndex++)
        {
            double rhat = parameterResults[parameterIndex].SummaryStatistics.Rhat;
            double ess = parameterResults[parameterIndex].SummaryStatistics.ESS;
            int modelParameterIndex = parameterIndex < derivedWeightIndex
                ? parameterIndex
                : parameterIndex + 1;
            string parameterName = model.Parameters[modelParameterIndex].Name;
            Assert.IsTrue(
                double.IsFinite(rhat) && rhat < 1.1,
                $"{parameterName} has R-hat {rhat:G6}; expected a finite value below 1.1.");
            Assert.IsTrue(
                double.IsFinite(ess) && ess >= RecoveryAcceptance.MinimumEffectiveSampleSize,
                $"{parameterName} has ESS {ess:G6}; expected a finite value at least {RecoveryAcceptance.MinimumEffectiveSampleSize:G6}.");
        }
    }

    /// <summary>
    /// Maps the generating continuous weights into the fitted model's fixed observed-atom simplex.
    /// </summary>
    /// <param name="model">The fitted mixture model.</param>
    /// <param name="generatingWeights">The generating unconditional continuous weights.</param>
    /// <returns>Full-K physical weights whose final coordinate closes the fitted component mass.</returns>
    private static double[] GetFittedCoordinateWeights(
        MixtureModel model,
        IReadOnlyList<double> generatingWeights)
    {
        double[] weights = generatingWeights.ToArray();
        double componentMass = model.IsZeroInflated ? 1.0 - model.Mixture!.ZeroWeight : 1.0;
        weights[^1] = componentMass - weights.Take(weights.Length - 1).Sum();
        Assert.IsTrue(weights.All(weight => double.IsFinite(weight) && weight > 0.0),
            "The fitted physical-weight crosswalk produced a nonpositive coordinate.");
        return weights;
    }

    /// <summary>
    /// Reconstructs the final physical weight in one K-1 posterior draw and orders components by mean.
    /// </summary>
    /// <param name="sampledParameters">The stored K-1 weight and component-parameter vector.</param>
    /// <param name="componentCount">The number of Normal components.</param>
    /// <param name="componentMass">The continuous mixture mass.</param>
    /// <returns>The physical components ordered by ascending mean.</returns>
    private static (double Weight, double[] Parameters)[] ExpandAndSortDraw(
        IReadOnlyList<double> sampledParameters,
        int componentCount,
        double componentMass)
    {
        int freeWeightCount = componentCount - 1;
        Assert.AreEqual(freeWeightCount + 2 * componentCount, sampledParameters.Count,
            "Stored mixture draw does not match the declared K-1 parameterization.");
        var weights = new double[componentCount];
        for (int i = 0; i < freeWeightCount; i++)
            weights[i] = sampledParameters[i];
        weights[^1] = componentMass - weights.Take(freeWeightCount).Sum();

        return weights
            .Select((weight, index) => (
                Weight: weight,
                Parameters: new[]
                {
                    sampledParameters[freeWeightCount + 2 * index],
                    sampledParameters[freeWeightCount + 2 * index + 1]
                }))
            .OrderBy(component => component.Parameters[0])
            .ToArray();
    }

    /// <summary>
    /// Creates a BestFit mixture model configured as the known synthetic parent.
    /// </summary>
    /// <param name="weights">The physical component weights.</param>
    /// <param name="distributions">The parent Normal components.</param>
    /// <param name="isZeroInflated">Whether the parent is a positive-hurdle mixture.</param>
    /// <param name="zeroWeight">The parent atom probability.</param>
    /// <returns>A BestFit model ready to generate the synthetic recovery sample.</returns>
    private static MixtureModel CreateGeneratingModel(
        double[] weights,
        IReadOnlyList<Normal> distributions,
        bool isZeroInflated,
        double zeroWeight)
    {
        var model = new MixtureModel(
            new BestFitDataFrame(),
            distributions.Select(distribution => distribution.Clone()).ToList(),
            isZeroInflated);
        model.Mixture!.ZeroWeight = zeroWeight;
        model.Mixture.SetParameters(
            weights.ToArray(),
            distributions.Select(distribution => distribution.Clone()).ToArray());
        return model;
    }

    /// <summary>
    /// Creates an exact annual data frame from the shared generated sample.
    /// </summary>
    /// <param name="sample">The generated sample.</param>
    /// <returns>A BestFit data frame containing the sample as exact annual records.</returns>
    private static BestFitDataFrame CreateDataFrame(double[] sample)
    {
        var exactData = sample
            .Select((value, index) => new ExactData { Index = index, Value = value })
            .ToList();
        return new BestFitDataFrame { ExactSeries = new ExactSeries(exactData) };
    }

    /// <summary>
    /// Creates the stable full-K BestFit parameter vector from physical weights and component parameters.
    /// </summary>
    /// <param name="weights">The physical component weights.</param>
    /// <param name="distributions">The component distributions.</param>
    /// <returns>The BestFit parameter vector.</returns>
    private static double[] CreateBestFitParameters(
        double[] weights,
        IReadOnlyList<Normal> distributions)
    {
        var parameters = new List<double>();
        if (weights.Length > 1)
            parameters.AddRange(weights);
        foreach (Normal distribution in distributions)
        {
            parameters.AddRange(distribution.GetParameters);
        }
        return parameters.ToArray();
    }

    /// <summary>
    /// Reconstructs all physical weights and component parameters from the full-K public vector.
    /// </summary>
    /// <param name="model">The fitted BestFit model.</param>
    /// <param name="parameters">The BestFit EM parameter vector.</param>
    /// <returns>A Numerics mixture carrying the fitted physical parameters.</returns>
    private static Mixture ReconstructBestFitMixture(
        MixtureModel model,
        double[] parameters)
    {
        int componentCount = model.Mixture!.Distributions.Length;
        int publicWeightCount = componentCount > 1 ? componentCount : 0;
        double componentMass = model.IsZeroInflated ? 1.0 - model.Mixture.ZeroWeight : 1.0;
        double[] weights = componentCount > 1
            ? parameters.Take(componentCount).ToArray()
            : new[] { componentMass };

        var result = (Mixture)model.Mixture.Clone();
        result.SetParameters(
            weights,
            parameters.Skip(publicWeightCount).ToArray());
        return result;
    }

    /// <summary>
    /// Sorts a fitted mixture by component mean to resolve label switching.
    /// </summary>
    /// <param name="mixture">The fitted mixture.</param>
    /// <returns>The physical weights and parameter arrays ordered by component mean.</returns>
    private static (double Weight, double[] Parameters)[] SortByComponentMean(
        Mixture mixture)
    {
        return mixture.Weights
            .Select((weight, index) => (
                Weight: weight,
                Parameters: mixture.Distributions[index].GetParameters))
            .OrderBy(component => component.Parameters[0])
            .ToArray();
    }

    /// <summary>
    /// Sorts a fitted mixture by mean while retaining each component's covariance index.
    /// </summary>
    /// <param name="mixture">The fitted mixture.</param>
    /// <returns>The indexed physical components ordered by ascending mean.</returns>
    private static (int OriginalIndex, double Weight, double[] Parameters)[] SortByComponentMeanWithIndex(
        Mixture mixture)
    {
        return mixture.Weights
            .Select((weight, index) => (
                OriginalIndex: index,
                Weight: weight,
                Parameters: mixture.Distributions[index].GetParameters))
            .OrderBy(component => component.Parameters[0])
            .ToArray();
    }
}
