using Numerics.Distributions;
using RMC.BestFit.Analyses;
using RMC.BestFit.Estimation;
using RMC.BestFit.Models;
using BestFitDataFrame = RMC.BestFit.Models.DataFrame;

namespace RMC.BestFit.Verification.Univariate.MixtureTests;

/// <summary>
/// Cross-engine recovery verification for finite Normal mixtures.
/// </summary>
[TestClass]
public class MixtureRecoveryTests
{
    /// <summary>
    /// Sample size for synthetic mixture generation and recovery.
    /// </summary>
    private const int SampleSize = 1000;

    /// <summary>
    /// Verifies recovery and cross-engine parity for a two-component Normal mixture.
    /// </summary>
    [TestMethod]
    public void NormalMixture2D_Recovery_Parity()
    {
        VerifyRecovery(
            generatingWeights: new[] { 0.3, 0.7 },
            generatingDistributions: new[]
            {
                new Normal(0.0, 1.0),
                new Normal(3.0, 0.1)
            },
            isZeroInflated: false,
            zeroWeight: 0.0);
    }

    /// <summary>
    /// Verifies recovery and cross-engine parity for a zero-inflated two-component Normal hurdle mixture.
    /// </summary>
    [TestMethod]
    public void ZeroInflatedNormalMixture2D_Recovery_Parity()
    {
        VerifyRecovery(
            generatingWeights: new[] { 0.3, 0.6 },
            generatingDistributions: new[]
            {
                new Normal(3.0, 0.1),
                new Normal(5.0, 2.0)
            },
            isZeroInflated: true,
            zeroWeight: 0.1);
    }

    /// <summary>
    /// Verifies recovery and cross-engine parity for a three-component Normal mixture.
    /// </summary>
    [TestMethod]
    public void NormalMixture3D_Recovery_Parity()
    {
        VerifyRecovery(
            generatingWeights: new[] { 0.2, 0.3, 0.5 },
            generatingDistributions: new[]
            {
                new Normal(0.0, 1.0),
                new Normal(3.0, 0.1),
                new Normal(5.0, 2.0)
            },
            isZeroInflated: false,
            zeroWeight: 0.0);
    }

    /// <summary>
    /// Verifies Bayesian recovery of a two-component Normal mixture generated by BestFit.
    /// </summary>
    /// <returns>A task representing the asynchronous Bayesian analysis.</returns>
    [TestMethod]
    public async Task NormalMixture2D_BayesianRecovery()
    {
        await VerifyBayesianRecoveryAsync(
            generatingWeights: new[] { 0.3, 0.7 },
            generatingDistributions: new[]
            {
                new Normal(0.0, 1.0),
                new Normal(3.0, 0.1)
            },
            isZeroInflated: false,
            zeroWeight: 0.0,
            samplerSeed: 22345);
    }

    /// <summary>
    /// Verifies Bayesian recovery of a zero-inflated two-component Normal hurdle mixture generated by BestFit.
    /// </summary>
    /// <returns>A task representing the asynchronous Bayesian analysis.</returns>
    [TestMethod]
    public async Task ZeroInflatedNormalMixture2D_BayesianRecovery()
    {
        await VerifyBayesianRecoveryAsync(
            generatingWeights: new[] { 0.3, 0.6 },
            generatingDistributions: new[]
            {
                new Normal(3.0, 0.1),
                new Normal(5.0, 2.0)
            },
            isZeroInflated: true,
            zeroWeight: 0.1,
            samplerSeed: 32345);
    }

    /// <summary>
    /// Verifies Bayesian recovery of a three-component Normal mixture generated by BestFit.
    /// </summary>
    /// <returns>A task representing the asynchronous Bayesian analysis.</returns>
    [TestMethod]
    public async Task NormalMixture3D_BayesianRecovery()
    {
        await VerifyBayesianRecoveryAsync(
            generatingWeights: new[] { 0.2, 0.3, 0.5 },
            generatingDistributions: new[]
            {
                new Normal(0.0, 1.0),
                new Normal(3.0, 0.1),
                new Normal(5.0, 2.0)
            },
            isZeroInflated: false,
            zeroWeight: 0.0,
            samplerSeed: 42345);
    }

    /// <summary>
    /// Generates one shared sample, compares pre-fit likelihoods, fits both engines, and checks parity and recovery.
    /// </summary>
    /// <param name="generatingWeights">The physical component weights.</param>
    /// <param name="generatingDistributions">The generating Normal components.</param>
    /// <param name="isZeroInflated">Whether to generate and fit a positive-hurdle mixture.</param>
    /// <param name="zeroWeight">The generating atom probability.</param>
    private static void VerifyRecovery(
        double[] generatingWeights,
        Normal[] generatingDistributions,
        bool isZeroInflated,
        double zeroWeight)
    {
        MixtureModel generator = CreateGeneratingModel(
            generatingWeights,
            generatingDistributions,
            isZeroInflated,
            zeroWeight);
        double[] sample = generator.GenerateRandomValues(SampleSize, 12345);
        Assert.AreEqual(
            SampleSize,
            sample.Length,
            "The BestFit mixture generator did not return the requested sample size.");
        BestFitDataFrame dataFrame = CreateDataFrame(sample);
        var distributionTypes = Enumerable
            .Repeat(UnivariateDistributionType.Normal, generatingDistributions.Length)
            .ToList();
        var bestFit = new MixtureModel(dataFrame, distributionTypes, isZeroInflated);

        double fittedZeroWeight = isZeroInflated ? bestFit.Mixture!.ZeroWeight : 0.0;
        double componentMass = 1.0 - fittedZeroWeight;
        double[] prefitWeights = generatingWeights.ToArray();
        if (isZeroInflated)
        {
            prefitWeights[^1] = componentMass - prefitWeights.Take(prefitWeights.Length - 1).Sum();
        }
        var numericsPrefit = new Mixture(
            prefitWeights,
            generatingDistributions.Select(distribution => distribution.Clone()).ToArray())
        {
            IsZeroInflated = isZeroInflated,
            ZeroWeight = fittedZeroWeight
        };
        double[] bestFitPrefitParameters = CreateBestFitParameters(
            prefitWeights,
            generatingDistributions);

        Assert.AreEqual(
            numericsPrefit.LogLikelihood(sample),
            bestFit.DataLogLikelihood(bestFitPrefitParameters),
            1E-10,
            "Pre-fit Numerics and BestFit data log likelihoods differ.");

        double initialWeight = componentMass / generatingWeights.Length;
        var numericsFit = new Mixture(
            Enumerable.Repeat(initialWeight, generatingWeights.Length).ToArray(),
            generatingDistributions
                .Select(_ => (UnivariateDistributionBase)new Normal())
                .ToArray())
        {
            IsZeroInflated = isZeroInflated,
            ZeroWeight = fittedZeroWeight
        };
        double[] numericsParameters = numericsFit.MLE(sample);
        numericsFit.SetParameters(numericsParameters);

        bestFit.ExpectationMaximization(
            out double[] bestFitParameters,
            out _,
            out _);
        Mixture bestFitFit = ReconstructBestFitMixture(bestFit, bestFitParameters);

        var numericsSorted = SortByComponentMean(numericsFit);
        var bestFitSorted = SortByComponentMean(bestFitFit);
        for (int componentIndex = 0; componentIndex < generatingWeights.Length; componentIndex++)
        {
            Assert.AreEqual(
                numericsSorted[componentIndex].Weight,
                bestFitSorted[componentIndex].Weight,
                1E-8,
                $"Cross-engine weight mismatch for component {componentIndex + 1}.");
            for (int parameterIndex = 0;
                 parameterIndex < numericsSorted[componentIndex].Parameters.Length;
                 parameterIndex++)
            {
                Assert.AreEqual(
                    numericsSorted[componentIndex].Parameters[parameterIndex],
                    bestFitSorted[componentIndex].Parameters[parameterIndex],
                    1E-8,
                    $"Cross-engine parameter mismatch for component {componentIndex + 1}, parameter {parameterIndex + 1}.");
            }
        }

        var generatingSorted = generatingWeights
            .Select((weight, index) => (
                Weight: weight,
                Parameters: generatingDistributions[index].GetParameters))
            .OrderBy(component => component.Parameters[0])
            .ToArray();
        for (int componentIndex = 0; componentIndex < generatingSorted.Length; componentIndex++)
        {
            Assert.AreEqual(
                generatingSorted[componentIndex].Weight,
                bestFitSorted[componentIndex].Weight,
                0.1,
                $"Weight recovery failed for component {componentIndex + 1}.");
            for (int parameterIndex = 0;
                 parameterIndex < generatingSorted[componentIndex].Parameters.Length;
                 parameterIndex++)
            {
                Assert.AreEqual(
                    generatingSorted[componentIndex].Parameters[parameterIndex],
                    bestFitSorted[componentIndex].Parameters[parameterIndex],
                    0.1,
                    $"Parameter recovery failed for component {componentIndex + 1}, parameter {parameterIndex + 1}.");
            }
        }
    }

    /// <summary>
    /// Generates a known parent sample through BestFit, fits it through <see cref="MixtureAnalysis"/>,
    /// and verifies Bayesian parameter recovery and chain diagnostics.
    /// </summary>
    /// <param name="generatingWeights">The physical component weights.</param>
    /// <param name="generatingDistributions">The generating Normal components.</param>
    /// <param name="isZeroInflated">Whether to generate and fit a positive-hurdle mixture.</param>
    /// <param name="zeroWeight">The generating atom probability.</param>
    /// <param name="samplerSeed">The deterministic MCMC seed.</param>
    /// <returns>A task representing the asynchronous Bayesian analysis.</returns>
    private static async Task VerifyBayesianRecoveryAsync(
        double[] generatingWeights,
        Normal[] generatingDistributions,
        bool isZeroInflated,
        double zeroWeight,
        int samplerSeed)
    {
        MixtureModel generator = CreateGeneratingModel(
            generatingWeights,
            generatingDistributions,
            isZeroInflated,
            zeroWeight);
        double[] sample = generator.GenerateRandomValues(SampleSize, 12345);
        Assert.AreEqual(
            SampleSize,
            sample.Length,
            "The BestFit mixture generator did not return the requested sample size.");

        BestFitDataFrame dataFrame = CreateDataFrame(sample);
        var distributionTypes = Enumerable
            .Repeat(UnivariateDistributionType.Normal, generatingDistributions.Length)
            .ToList();
        var model = new MixtureModel(dataFrame, distributionTypes, isZeroInflated);
        MixtureAnalysis analysis = ConfigureBayesianAnalysis(model, samplerSeed);
        Exception? analysisError = null;
        analysis.AnalysisCompleted += (_, args) => analysisError = args.Error;

        var validation = analysis.Validate();
        Assert.IsTrue(validation.IsValid, string.Join(Environment.NewLine, validation.ValidationMessages));

        await analysis.RunAsync();

        Assert.IsTrue(
            analysis.IsEstimated,
            $"Bayesian mixture recovery did not complete. {analysisError ?? analysis.BayesianAnalysis.LastError}");
        Assert.IsNotNull(analysis.BayesianAnalysis.Results, "Bayesian mixture results are null.");

        if (isZeroInflated)
        {
            double zeroStandardError = Math.Sqrt(zeroWeight * (1.0 - zeroWeight) / SampleSize);
            Assert.AreEqual(
                zeroWeight,
                model.Mixture!.ZeroWeight,
                5.0 * zeroStandardError,
                "The BestFit-generated zero atom missed its binomial Monte Carlo bound.");
        }

        var pointEstimate = (Mixture?)analysis.GetPointEstimateDistribution(
            BayesianAnalysis.PointEstimateType.PosteriorMode);
        Assert.IsNotNull(pointEstimate, "The Bayesian posterior-mode mixture is null.");
        AssertBayesianRecovery(
            generatingWeights,
            generatingDistributions,
            pointEstimate!);
        AssertBayesianDiagnostics(model, analysis);
    }

    /// <summary>
    /// Configures the shared DEMCzs recovery analysis using the established verification pattern.
    /// </summary>
    /// <param name="model">The mixture model to estimate.</param>
    /// <param name="seed">The deterministic sampler seed.</param>
    /// <returns>A configured Bayesian mixture analysis.</returns>
    private static MixtureAnalysis ConfigureBayesianAnalysis(MixtureModel model, int seed)
    {
        var analysis = new MixtureAnalysis(model);
        analysis.BayesianAnalysis.UseSimulationDefaults = false;
        analysis.BayesianAnalysis.Type = BayesianAnalysis.SamplerType.DEMCzs;
        analysis.BayesianAnalysis.NumberOfChains = 4;
        analysis.BayesianAnalysis.WarmupIterations = 1500;
        analysis.BayesianAnalysis.Iterations = 3000;
        analysis.BayesianAnalysis.ThinningInterval = 5;
        analysis.BayesianAnalysis.PRNGSeed = seed;
        analysis.BayesianAnalysis.InitialIterations = Math.Min(1000, Math.Max(100, model.NumberOfParameters * 100));
        analysis.BayesianAnalysis.OutputLength = 5000;
        analysis.BayesianAnalysis.CredibleIntervalWidth = 0.9;
        analysis.BayesianAnalysis.PointEstimator = BayesianAnalysis.PointEstimateType.PosteriorMode;
        return analysis;
    }

    /// <summary>
    /// Verifies posterior-mode component weights and Normal parameters after resolving label order by mean.
    /// </summary>
    /// <param name="generatingWeights">The true physical component weights.</param>
    /// <param name="generatingDistributions">The true Normal components.</param>
    /// <param name="fittedMixture">The posterior-mode mixture.</param>
    private static void AssertBayesianRecovery(
        double[] generatingWeights,
        IReadOnlyList<Normal> generatingDistributions,
        Mixture fittedMixture)
    {
        var expected = generatingWeights
            .Select((weight, index) => (
                Weight: weight,
                Parameters: generatingDistributions[index].GetParameters))
            .OrderBy(component => component.Parameters[0])
            .ToArray();
        var actual = SortByComponentMean(fittedMixture);

        Assert.AreEqual(expected.Length, actual.Length, "Bayesian mixture component count mismatch.");
        for (int componentIndex = 0; componentIndex < expected.Length; componentIndex++)
        {
            Assert.AreEqual(
                expected[componentIndex].Weight,
                actual[componentIndex].Weight,
                0.1,
                $"Bayesian weight recovery failed for component {componentIndex + 1}.");

            for (int parameterIndex = 0;
                 parameterIndex < expected[componentIndex].Parameters.Length;
                 parameterIndex++)
            {
                double trueValue = expected[componentIndex].Parameters[parameterIndex];
                double tolerance = Math.Max(0.15, Math.Abs(trueValue) * 0.15);
                Assert.AreEqual(
                    trueValue,
                    actual[componentIndex].Parameters[parameterIndex],
                    tolerance,
                    $"Bayesian parameter recovery failed for component {componentIndex + 1}, " +
                    $"parameter {parameterIndex + 1}.");
            }
        }
    }

    /// <summary>
    /// Verifies split R-hat and conservative effective sample size for every sampled mixture parameter.
    /// </summary>
    /// <param name="model">The fitted mixture model.</param>
    /// <param name="analysis">The completed Bayesian analysis.</param>
    private static void AssertBayesianDiagnostics(MixtureModel model, MixtureAnalysis analysis)
    {
        var parameterResults = analysis.BayesianAnalysis.Results!.ParameterResults;
        int derivedWeightIndex = model.Mixture!.Distributions!.Length - 1;
        int sampledParameterCount = model.NumberOfParameters - 1;
        Assert.AreEqual(sampledParameterCount, parameterResults.Length, "MCMC sampled diagnostic parameter count mismatch.");
        for (int parameterIndex = 0; parameterIndex < parameterResults.Length; parameterIndex++)
        {
            double rhat = parameterResults[parameterIndex].SummaryStatistics.Rhat;
            double ess = parameterResults[parameterIndex].SummaryStatistics.ESS;
            int modelParameterIndex = parameterIndex < derivedWeightIndex
                ? parameterIndex
                : parameterIndex + 1;
            string parameterName = model.Parameters[modelParameterIndex].Name;
            Assert.IsTrue(
                double.IsFinite(rhat) && rhat < 1.1,
                $"{parameterName} has R-hat {rhat:G6}; expected a finite value below 1.1.");
            Assert.IsTrue(
                double.IsFinite(ess) && ess > 100.0,
                $"{parameterName} has ESS {ess:G6}; expected a finite value above 100.");
        }
    }

    /// <summary>
    /// Creates a BestFit mixture model configured as the known synthetic parent.
    /// </summary>
    /// <param name="weights">The physical component weights.</param>
    /// <param name="distributions">The parent Normal components.</param>
    /// <param name="isZeroInflated">Whether the parent is a positive-hurdle mixture.</param>
    /// <param name="zeroWeight">The parent atom probability.</param>
    /// <returns>A BestFit model ready to generate the synthetic recovery sample.</returns>
    private static MixtureModel CreateGeneratingModel(
        double[] weights,
        IReadOnlyList<Normal> distributions,
        bool isZeroInflated,
        double zeroWeight)
    {
        var model = new MixtureModel(
            new BestFitDataFrame(),
            distributions.Select(distribution => distribution.Clone()).ToList(),
            isZeroInflated);
        model.Mixture!.ZeroWeight = zeroWeight;
        model.Mixture.SetParameters(
            weights.ToArray(),
            distributions.Select(distribution => distribution.Clone()).ToArray());
        return model;
    }

    /// <summary>
    /// Creates an exact annual data frame from the shared generated sample.
    /// </summary>
    /// <param name="sample">The generated sample.</param>
    /// <returns>A BestFit data frame containing the sample as exact annual records.</returns>
    private static BestFitDataFrame CreateDataFrame(double[] sample)
    {
        var exactData = sample
            .Select((value, index) => new ExactData { Index = index, Value = value })
            .ToList();
        return new BestFitDataFrame { ExactSeries = new ExactSeries(exactData) };
    }

    /// <summary>
    /// Creates the stable full-K BestFit parameter vector from physical weights and component parameters.
    /// </summary>
    /// <param name="weights">The physical component weights.</param>
    /// <param name="distributions">The component distributions.</param>
    /// <returns>The BestFit parameter vector.</returns>
    private static double[] CreateBestFitParameters(
        double[] weights,
        IReadOnlyList<Normal> distributions)
    {
        var parameters = new List<double>();
        if (weights.Length > 1)
            parameters.AddRange(weights);
        foreach (Normal distribution in distributions)
        {
            parameters.AddRange(distribution.GetParameters);
        }
        return parameters.ToArray();
    }

    /// <summary>
    /// Reconstructs all physical weights and component parameters from the full-K public vector.
    /// </summary>
    /// <param name="model">The fitted BestFit model.</param>
    /// <param name="parameters">The BestFit EM parameter vector.</param>
    /// <returns>A Numerics mixture carrying the fitted physical parameters.</returns>
    private static Mixture ReconstructBestFitMixture(
        MixtureModel model,
        double[] parameters)
    {
        int componentCount = model.Mixture!.Distributions.Length;
        int publicWeightCount = componentCount > 1 ? componentCount : 0;
        double componentMass = model.IsZeroInflated ? 1.0 - model.Mixture.ZeroWeight : 1.0;
        double[] weights = componentCount > 1
            ? parameters.Take(componentCount).ToArray()
            : new[] { componentMass };

        var result = (Mixture)model.Mixture.Clone();
        result.SetParameters(
            weights,
            parameters.Skip(publicWeightCount).ToArray());
        return result;
    }

    /// <summary>
    /// Sorts a fitted mixture by component mean to resolve label switching.
    /// </summary>
    /// <param name="mixture">The fitted mixture.</param>
    /// <returns>The physical weights and parameter arrays ordered by component mean.</returns>
    private static (double Weight, double[] Parameters)[] SortByComponentMean(
        Mixture mixture)
    {
        return mixture.Weights
            .Select((weight, index) => (
                Weight: weight,
                Parameters: mixture.Distributions[index].GetParameters))
            .OrderBy(component => component.Parameters[0])
            .ToArray();
    }
}
